"""Translated messages for Uzbek, «Yangi o‘zbek», Karakalpak, Russian, and English."""

from __future__ import annotations

import re

from .localization_kaa import KARAKALPAK_TEXTS

# "uzn" is «Yangi o‘zbek» — the same Uzbek interface written with the letters
# ö, ğ, ş, and ç. "kaa" is the full Karakalpak translation.
LANGUAGES = ("uz", "uzn", "kaa", "ru", "en")
LANGUAGE_NAMES = {
    "uz": "🇺🇿 O‘zbekcha",
    "uzn": "🇺🇿 Yangi o‘zbek (ö, ğ, ş, ç)",
    "kaa": "🇺🇿 Qaraqalpaqsha",
    "ru": "🇷🇺 Русский",
    "en": "🇬🇧 English",
}

TEXTS: dict[str, dict[str, str]] = {
    "welcome": {
        "uz": "Quest Bot’ga xush kelibsiz! Kvestlarni toping, qatnashing yoki o‘zingiz yarating.",
        "ru": "Добро пожаловать в Quest Bot! Находите квесты, участвуйте или создавайте свои.",
        "en": "Welcome to Quest Bot! Discover quests, participate, or create your own.",
    },
    "menu": {"uz": "Asosiy menyu", "ru": "Главное меню", "en": "Main menu"},
    "btn_quests": {"uz": "🔎 Kvestlarni ko‘rish", "ru": "🔎 Список квестов", "en": "🔎 Browse quests"},
    "btn_my_quests": {"uz": "🛠️ Men boshqaradigan kvestlar", "ru": "🛠️ Квесты под моим управлением", "en": "🛠️ Quests I manage"},
    "btn_my_participations": {"uz": "🙋 Qatnashayotgan kvestlar", "ru": "🙋 Квесты, в которых я участвую", "en": "🙋 My joined quests"},
    "btn_admin": {"uz": "🛠️ Administrator paneli", "ru": "🛠️ Панель администратора", "en": "🛠️ Admin panel"},
    "btn_ratings": {"uz": "🏆 Reytinglar", "ru": "🏆 Рейтинги", "en": "🏆 Leaderboards"},
    "btn_public_quest_ratings": {"uz": "🏆 Ommaviy kvestlar reytingi", "ru": "🏆 Рейтинги публичных квестов", "en": "🏆 Public quest ratings"},
    "btn_managed_ratings": {"uz": "🏆 Boshqariladigan kvestlar reytingi", "ru": "🏆 Рейтинги управляемых квестов", "en": "🏆 Managed quest ratings"},
    "period_week": {"uz": "📅 Shu hafta", "ru": "📅 Эта неделя", "en": "📅 This week"},
    "period_month": {"uz": "📆 Shu oy", "ru": "📆 Этот месяц", "en": "📆 This month"},
    "period_year": {"uz": "🗓 Shu yil", "ru": "🗓 Этот год", "en": "🗓 This year"},
    "btn_guide": {"uz": "📖 Yo‘riqnoma", "ru": "📖 Инструкция", "en": "📖 How to use"},
    "btn_support": {"uz": "💬 Yordam / murojaat", "ru": "💬 Поддержка", "en": "💬 Support"},
    "btn_language": {"uz": "🌐 Tilni tanlash", "ru": "🌐 Выбрать язык", "en": "🌐 Choose language"},
    "btn_back": {"uz": "⬅️ Orqaga", "ru": "⬅️ Назад", "en": "⬅️ Back"},
    "btn_home": {"uz": "🏠 Bosh menyu", "ru": "🏠 Главное меню", "en": "🏠 Main menu"},
    "btn_admin_home": {"uz": "🛠 Administrator paneli", "ru": "🛠 Панель администратора", "en": "🛠 Admin panel"},
    "btn_cancel": {"uz": "❌ Bekor qilish", "ru": "❌ Отмена", "en": "❌ Cancel"},
    "btn_confirm": {"uz": "✅ Tasdiqlash", "ru": "✅ Подтвердить", "en": "✅ Confirm"},
    "btn_join": {"uz": "✅ Qatnashish", "ru": "✅ Участвовать", "en": "✅ Join"},
    "btn_confirm_join": {"uz": "✅ Qatnashishni tasdiqlash", "ru": "✅ Подтвердить участие", "en": "✅ Confirm join"},
    "btn_skip_photo": {"uz": "⏭️ Rasmsiz davom etish", "ru": "⏭️ Продолжить без фото", "en": "⏭️ Skip photo"},
    "btn_edit_details": {"uz": "🛠 Kvest tafsilotlarini tahrirlash", "ru": "🛠 Редактировать данные квеста", "en": "🛠 Edit quest details"},
    "btn_edit_title": {"uz": "✏️ Nomini tahrirlash", "ru": "✏️ Изменить название", "en": "✏️ Edit title"},
    "btn_edit_description": {"uz": "📝 Tavsifni tahrirlash", "ru": "📝 Изменить описание", "en": "📝 Edit description"},
    "btn_edit_cover": {"uz": "🖼 Muqova rasmini tahrirlash", "ru": "🖼 Изменить обложку", "en": "🖼 Edit cover photo"},
    "btn_replace_cover": {"uz": "📷 Rasm qo‘shish yoki almashtirish", "ru": "📷 Добавить или заменить фото", "en": "📷 Add or replace photo"},
    "btn_remove_cover": {"uz": "🗑️ Muqova rasmini olib tashlash", "ru": "🗑️ Удалить обложку", "en": "🗑️ Remove cover photo"},
    "btn_confirm_remove_cover": {"uz": "🗑️ Ha, olib tashlash", "ru": "🗑️ Да, удалить", "en": "🗑️ Yes, remove it"},
    "btn_private_link": {"uz": "🔗 Kvest taklif havolasini olish", "ru": "🔗 Получить ссылку на квест", "en": "🔗 Get private quest link"},
    "btn_open": {"uz": "👁️ Ko‘rish", "ru": "👁️ Открыть", "en": "👁️ Open"},
    "btn_create": {"uz": "➕ Kvest yaratish", "ru": "➕ Создать квест", "en": "➕ Create quest"},
    "btn_manage": {"uz": "⚙️ Boshqarish", "ru": "⚙️ Управление", "en": "⚙️ Manage"},
    "btn_edit_questions": {"uz": "✏️ Savollarni tahrirlash", "ru": "✏️ Редактировать вопросы", "en": "✏️ Edit questions"},
    "btn_edit_question": {"uz": "✏️ Savolni o‘zgartirish", "ru": "✏️ Изменить вопрос", "en": "✏️ Edit question"},
    "btn_add_stage": {"uz": "➕ Bosqich qo‘shish", "ru": "➕ Добавить этап", "en": "➕ Add stage"},
    "btn_remove_stage": {"uz": "🗑️ Bosqichni olib tashlash", "ru": "🗑️ Удалить этап", "en": "🗑️ Remove stage"},
    "btn_confirm_remove_stage": {"uz": "🗑️ Ha, olib tashlash", "ru": "🗑️ Да, удалить", "en": "🗑️ Yes, remove"},
    "btn_edit_answer": {"uz": "✏️ To‘g‘ri javobni o‘zgartirish", "ru": "✏️ Изменить правильный ответ", "en": "✏️ Edit correct answer"},
    "btn_rank": {"uz": "🏆 Reyting", "ru": "🏆 Рейтинг", "en": "🏆 Leaderboard"},
    "btn_participants": {"uz": "👥 Ishtirokchilar", "ru": "👥 Участники", "en": "👥 Participants"},
    "btn_pending": {"uz": "🔎 Tekshiruvdagi javoblar", "ru": "🔎 Ответы на проверке", "en": "🔎 Pending answers"},
    "btn_invite": {"uz": "🔗 Chatga bir kishilik havola", "ru": "🔗 Одноразовая ссылка в чат", "en": "🔗 One-person chat invite"},
    "btn_finish": {"uz": "🏁 Kvestni yakunlash", "ru": "🏁 Завершить квест", "en": "🏁 Finish quest"},
    "btn_pause": {"uz": "⏸️ Kvestni vaqtincha to‘xtatish", "ru": "⏸️ Приостановить квест", "en": "⏸️ Pause quest"},
    "btn_resume": {"uz": "▶️ Kvestni davom ettirish", "ru": "▶️ Возобновить квест", "en": "▶️ Resume quest"},
    "btn_archive": {"uz": "📦 Arxivlash", "ru": "📦 Архивировать", "en": "📦 Archive"},
    "btn_unarchive": {"uz": "📤 Arxivdan chiqarish", "ru": "📤 Убрать из архива", "en": "📤 Unarchive"},
    "btn_ban": {"uz": "🚫 Bloklash", "ru": "🚫 Заблокировать", "en": "🚫 Block"},
    "btn_unban": {"uz": "✅ Blokdan chiqarish", "ru": "✅ Разблокировать", "en": "✅ Unblock"},
    "btn_approve": {"uz": "✅ To‘g‘ri", "ru": "✅ Верно", "en": "✅ Approve"},
    "btn_reject": {"uz": "❌ Noto‘g‘ri", "ru": "❌ Неверно", "en": "❌ Reject"},
    "btn_skip": {"uz": "⏭️ Sababsiz davom etish", "ru": "⏭️ Без причины", "en": "⏭️ Skip reason"},
    "btn_add": {"uz": "➕ Qo‘shish", "ru": "➕ Добавить", "en": "➕ Add"},
    "btn_remove": {"uz": "🗑️ Olib tashlash", "ru": "🗑️ Удалить", "en": "🗑️ Remove"},
    "btn_toggle_cleanup": {"uz": "🧹 Chiqarish sozlamasini o‘zgartirish", "ru": "🧹 Изменить очистку участников", "en": "🧹 Toggle member cleanup"},
    "btn_whitelist": {"uz": "🛡️ Istisnolar ro‘yxati", "ru": "🛡️ Список исключений", "en": "🛡️ Whitelist"},
    "btn_admins": {"uz": "👥 Administratorlarni boshqarish", "ru": "👥 Администраторы", "en": "👥 Manage admins"},
    "btn_stats": {"uz": "📊 Statistika", "ru": "📊 Статистика", "en": "📊 Statistics"},
    "btn_logs": {"uz": "📜 Harakatlar jurnali", "ru": "📜 Журнал действий", "en": "📜 Audit log"},
    "btn_settings": {"uz": "⚙️ Sozlamalar", "ru": "⚙️ Настройки", "en": "⚙️ Settings"},
    "btn_export": {"uz": "📤 Ma’lumotlarni eksport qilish", "ru": "📤 Экспорт данных", "en": "📤 Export data"},
    "btn_chats": {"uz": "📣 Guruh/kanallar", "ru": "📣 Группы/каналы", "en": "📣 Groups/channels"},
    "btn_support_super": {"uz": "👑 Bosh administratorga yozish", "ru": "👑 Написать суперадминистратору", "en": "👑 Contact superadmin"},
    "btn_support_quest": {"uz": "👤 Kvest administratoriga yozish", "ru": "👤 Написать админу квеста", "en": "👤 Contact quest admin"},
    "btn_my_tickets": {"uz": "🎫 Mening murojaatlarim", "ru": "🎫 Мои обращения", "en": "🎫 My tickets"},
    "btn_reply": {"uz": "↩️ Javob yozish", "ru": "↩️ Ответить", "en": "↩️ Reply"},
    "btn_reply_ticket": {"uz": "↩️ Javob berish", "ru": "↩️ Ответить", "en": "↩️ Reply"},
    "open_private_chat": {"uz": "🔒 Davom etish uchun botni shaxsiy chatda oching.", "ru": "🔒 Чтобы продолжить, откройте бота в личном чате.", "en": "🔒 Open the bot in a private chat to continue."},
    "chat_id_result": {"uz": "Chat ID: {chat_id}\nNomi: {title}", "ru": "Chat ID: {chat_id}\nНазвание: {title}", "en": "Chat ID: {chat_id}\nTitle: {title}"},
    "welcome_hint": {
        "uz": "Tilni almashtirish uchun /language buyrug‘idan foydalaning.",
        "ru": "Чтобы сменить язык, используйте команду /language.",
        "en": "Use /language to change the interface language.",
    },
    "guide": {
        "uz": "Yo‘riqnoma:\n1. “Kvestlarni ko‘rish” orqali ommaviy kvestlarni toping. Maxfiy kvest botning taklif havolasi orqali ochiladi.\n2. Kvest boshlanganda xabar keladi; savol «Boshlash»/«Davom etish» tugmasi bosilganda botning shaxsiy chatiga yuboriladi. Kvestga biriktirilgan guruh/kanal bo‘lsa, e’lonlar u yerda chiqadi; javoblar botga shaxsiy chatda yuboriladi.\n3. Javob saqlangan javob bilan aynan solishtiriladi; bosh/oxiridagi bo‘sh joylar olib tashlanadi, katta-kichik harf farqi saqlanadi. Administrator tekshiradigan bosqichlarda natijani administrator belgilaydi.\n4. Reytingni kvest sahifasidan yoki “Reytinglar”dan kuzating.\n5. Yordam orqali bosh administratorga yoki tegishli kvest administratoriga yozing.\n\nAdministrator o‘z kvestini yaratadi va boshqaradi; boshqariladigan kvestlar ro‘yxati «Administrator paneli» ichida. Bosh administrator administratorlar, barcha kvestlar, arxiv, statistika, harakatlar jurnali va sozlamalarni boshqaradi. Botda reklama yo‘q.",
        "ru": "Инструкция:\n1. Ищите публичные квесты в «Список квестов». Приватный квест открывается по ссылке-приглашению бота.\n2. Когда квест начинается, приходит уведомление; вопрос отправляется в личный чат с ботом после нажатия «Начать»/«Продолжить». Если квест привязан к группе/каналу, объявления публикуются там; ответы отправляются боту в личку.\n3. Ответ сравнивается с эталоном точно; крайние пробелы удаляются, регистр учитывается. На этапах с ручной проверкой результат выставляет администратор.\n4. Рейтинг доступен на странице квеста и в разделе «Рейтинги».\n5. Через поддержку можно написать суперадминистратору или админу квеста.\n\nАдминистратор создаёт и ведёт свои квесты; список управляемых квестов находится в «Панели администратора». Суперадминистратор управляет всеми квестами, администраторами, архивом, статистикой, журналом и настройками. Рекламы нет.",
        "en": "Guide:\n1. Find public quests in “Browse quests”. Private quests open through the bot’s invitation link.\n2. When a quest starts you get a notice; the question is delivered in the bot’s private chat after you press Start/Continue. If a group/channel is attached, announcements appear there; answers are sent privately to the bot.\n3. Answers are compared exactly with the stored answer; leading/trailing whitespace is trimmed and letter case matters. Stages with manual checking are reviewed by an admin.\n4. View rankings on the quest page or in “Leaderboards”.\n5. Use Support to contact the superadmin or the relevant quest admin.\n\nAdmins create and run their own quests; the list of managed quests lives inside the Admin panel. The superadmin controls all quests, admins, archives, statistics, logs, and settings. No advertising is included.",
    },
    "language_choose": {"uz": "🌐 Interfeys tilini tanlang:", "ru": "🌐 Выберите язык интерфейса:", "en": "🌐 Choose your interface language:"},
    "language_saved": {"uz": "✅ Til O‘zbekcha qilib saqlandi.", "ru": "✅ Язык сохранён: русский.", "en": "✅ Language saved: English."},
    "language_button": {"uz": "O‘zbekcha", "ru": "O‘zbekcha", "en": "O‘zbekcha"},
    "quests_title": {"uz": "🔎 Ommaviy kvestlar", "ru": "🔎 Публичные квесты", "en": "🔎 Public quests"},
    "my_quests_title": {"uz": "🛠️ Boshqariladigan kvestlar", "ru": "🛠️ Квесты под вашим управлением", "en": "🛠️ Quests you manage"},
    "my_participating_quests_title": {"uz": "🙋 Siz qatnashayotgan kvestlar", "ru": "🙋 Квесты, в которых вы участвуете", "en": "🙋 Quests you have joined"},
    "empty_quests": {"uz": "📭 Bu bo‘limda kvest topilmadi.", "ru": "📭 В этом разделе квестов нет.", "en": "📭 No quests found in this section."},
    "filter_all": {"uz": "📋 Barchasi", "ru": "📋 Все", "en": "📋 All"},
    "filter_scheduled": {"uz": "🕒 Kutilmoqda", "ru": "🕒 Ожидают начала", "en": "🕒 Upcoming"},
    "filter_active": {"uz": "🟢 Davom etmoqda", "ru": "🟢 Идут", "en": "🟢 Ongoing"},
    "filter_completed": {"uz": "✅ Yakunlangan", "ru": "✅ Завершены", "en": "✅ Completed"},
    "filter_archived": {"uz": "🗄️ Arxivlangan", "ru": "🗄️ В архиве", "en": "🗄️ Archived"},
    "status_scheduled": {"uz": "🕒 Kutilmoqda", "ru": "🕒 Ожидает", "en": "🕒 Upcoming"},
    "status_active": {"uz": "🟢 Davom etmoqda", "ru": "🟢 Идёт", "en": "🟢 Ongoing"},
    "status_completed": {"uz": "✅ Yakunlangan", "ru": "✅ Завершён", "en": "✅ Completed"},
    "status_archived": {"uz": "🗄️ Arxivlangan", "ru": "🗄️ В архиве", "en": "🗄️ Archived"},
    "status_paused": {"uz": "⏸️ Vaqtincha to‘xtatilgan", "ru": "⏸️ Приостановлен", "en": "⏸️ Paused"},
    "visibility_public": {"uz": "🌐 Ommaviy", "ru": "🌐 Публичный", "en": "🌐 Public"},
    "visibility_private": {"uz": "🔒 Maxfiy", "ru": "🔒 Приватный", "en": "🔒 Private"},
    "progression_immediate": {"uz": "⚡ To‘g‘ri javobdan keyin darhol", "ru": "⚡ Сразу после правильного ответа", "en": "⚡ Immediately after a correct answer"},
    "progression_scheduled": {"uz": "📅 Jadval bo‘yicha", "ru": "📅 По расписанию", "en": "📅 At scheduled times"},
    "answer_auto": {"uz": "🤖 Avtomatik tekshiruv", "ru": "🤖 Автоматическая проверка", "en": "🤖 Automatic checking"},
    "answer_manual": {"uz": "👤 Administrator tekshiradi", "ru": "👤 Проверяет администратор", "en": "👤 Admin review"},
    "quest_card": {"uz": "{title}\nHolati: {status}\nBoshlanishi: {start}\nBosqichlar: {stages}\nTuri: {visibility}", "ru": "{title}\nСтатус: {status}\nНачало: {start}\nЭтапов: {stages}\nТип: {visibility}", "en": "{title}\nStatus: {status}\nStarts: {start}\nStages: {stages}\nVisibility: {visibility}"},
    "quest_details": {"uz": "{title}\n\n{description}\n\nHolati: {status}\nTuri: {visibility}\nBoshlanishi: {start}\nBosqichlar: {stages}\nKeyingi bosqich: {progression}\nUmumiy vaqt: {duration}\nSavollar guruhi: {chat}\nQatnashchilar: {participants}", "ru": "{title}\n\n{description}\n\nСтатус: {status}\nТип: {visibility}\nНачало: {start}\nЭтапов: {stages}\nПереход: {progression}\nОбщее время: {duration}\nЧат вопросов: {chat}\nУчастников: {participants}", "en": "{title}\n\n{description}\n\nStatus: {status}\nVisibility: {visibility}\nStarts: {start}\nStages: {stages}\nProgression: {progression}\nOverall time: {duration}\nQuestion chat: {chat}\nParticipants: {participants}"},
    "quest_label_description": {"uz": "Tavsif", "ru": "Описание", "en": "Description"},
    "quest_label_status": {"uz": "Holati", "ru": "Статус", "en": "Status"},
    "quest_label_visibility": {"uz": "Turi", "ru": "Тип", "en": "Visibility"},
    "quest_label_start": {"uz": "Boshlanish vaqti", "ru": "Время начала", "en": "Start time"},
    "quest_label_stages": {"uz": "Bosqichlar soni", "ru": "Количество этапов", "en": "Stage count"},
    "quest_label_participants": {"uz": "Qatnashchilar soni", "ru": "Количество участников", "en": "Participants"},
    "quest_label_progression": {"uz": "Keyingi bosqich", "ru": "Переход к этапам", "en": "Progression"},
    "quest_label_duration": {"uz": "Umumiy vaqt", "ru": "Общее время", "en": "Overall time"},
    "quest_label_chat": {"uz": "Savollar guruhi", "ru": "Чат вопросов", "en": "Question chat"},
    "quest_not_found": {"uz": "⚠️ Kvest topilmadi yoki unga kirish huquqingiz yo‘q.", "ru": "⚠️ Квест не найден или у вас нет доступа.", "en": "⚠️ Quest not found or you do not have access."},
    "join_success": {"uz": "✅ Kvestga qo‘shildingiz. Kvest boshlanganda sizga xabar beriladi; savol «Boshlash» tugmasi bosilganda yuboriladi.", "ru": "✅ Вы присоединились к квесту. Когда квест начнётся, придёт уведомление; вопрос отправляется после нажатия «Начать».", "en": "✅ You joined the quest. You will be notified when it starts; the question is sent after you press Start."},
    "already_joined": {"uz": "Siz bu kvestda allaqachon qatnashyapsiz.", "ru": "Вы уже участвуете в этом квесте.", "en": "You have already joined this quest."},
    "join_closed": {"uz": "Bu kvestga qo‘shilish yopilgan.", "ru": "В этот квест больше нельзя вступить.", "en": "Joining this quest is closed."},
    "join_confirmation_prompt": {"uz": "Kvestga qo‘shilishni tasdiqlaysizmi?", "ru": "Подтвердить участие в квесте?", "en": "Do you want to confirm joining this quest?"},
    "join_cancelled": {"uz": "Kvestga qo‘shilish bekor qilindi.", "ru": "Вступление в квест отменено.", "en": "Joining the quest was cancelled."},
    "quest_paused_notice": {"uz": "Kvest vaqtincha to‘xtatilgan. Davom ettirilgach, qayta urinib ko‘ring.", "ru": "Квест временно приостановлен. Повторите действие после возобновления.", "en": "This quest is paused. Please try again after it resumes."},
    "pause_success": {"uz": "Kvest vaqtincha to‘xtatildi. Jadval va muddatlar shu vaqt davomida hisoblanmaydi.", "ru": "Квест приостановлен. Расписание и сроки заморожены на время паузы.", "en": "Quest paused. Schedules and deadlines are frozen until it resumes."},
    "resume_success": {"uz": "Kvest davom ettirildi. Jadval va muddatlar to‘xtatilgan vaqtga surildi.", "ru": "Квест возобновлён. Расписание и сроки сдвинуты на время паузы.", "en": "Quest resumed. Schedules and deadlines shifted by the paused duration."},
    "private_link_invalid": {"uz": "Maxfiy kvest havolasi noto‘g‘ri yoki bekor qilingan.", "ru": "Ссылка на приватный квест неверна или отменена.", "en": "This private quest link is invalid or has been revoked."},
    "global_blocked": {"uz": "Botdan foydalanishingiz bloklangan.{reason}", "ru": "Доступ к боту заблокирован.{reason}", "en": "Your access to the bot is blocked.{reason}"},
    "blocked_notice": {"uz": "Siz ushbu kvestdan bloklandingiz.{reason}", "ru": "Вы заблокированы в этом квесте.{reason}", "en": "You have been blocked from this quest.{reason}"},
    "warning_blocked": {"uz": "⚠️ Siz “{title}” kvestidan bloklandingiz.{reason}", "ru": "⚠️ Вы заблокированы в квесте «{title}».{reason}", "en": "⚠️ You have been blocked from “{title}”.{reason}"},
    "reason_line": {"uz": " Sabab: {reason}", "ru": " Причина: {reason}", "en": " Reason: {reason}"},
    "btn_answer_privately": {"uz": "✉️ Javobni botga yuborish", "ru": "✉️ Ответить боту", "en": "✉️ Answer privately"},
    "ask_title": {"uz": "✏️ Kvest nomini yuboring:", "ru": "✏️ Отправьте название квеста:", "en": "✏️ Send the quest title:"},
    "ask_description": {"uz": "📝 Kvest tavsifini yuboring:", "ru": "📝 Отправьте описание квеста:", "en": "📝 Send the quest description:"},
    "ask_cover_photo": {"uz": "📷 Kvest muqovasi uchun rasm yuboring yoki rasm qo‘shmasdan davom eting:", "ru": "📷 Отправьте обложку квеста или продолжите без фото:", "en": "📷 Send an optional quest cover photo, or continue without one:"},
    "invalid_cover_photo": {"uz": "Muqova uchun rasm yuboring yoki «Rasmsiz davom etish» tugmasini bosing.", "ru": "Отправьте фото для обложки или нажмите «Продолжить без фото».", "en": "Send a photo for the cover or choose Skip photo."},
    "ask_visibility": {"uz": "🌐 Kvest turi:", "ru": "🌐 Тип квеста:", "en": "🌐 Choose quest visibility:"},
    "ask_stage_count": {"uz": "Bosqichlar sonini kiriting (1–30):", "ru": "Укажите количество этапов (1–30):", "en": "Enter the number of stages (1–30):"},
    "ask_progression": {"uz": "⚙️ Keyingi bosqich qanday yuborilsin?", "ru": "⚙️ Как отправлять следующий этап?", "en": "⚙️ How should the next stage be delivered?"},
    "ask_start": {"uz": "Boshlanish vaqtini Toshkent vaqti bo‘yicha kiriting: YYYY-MM-DD HH:MM\nMasalan: 2026-10-03 18:30", "ru": "Введите время начала по Ташкенту: YYYY-MM-DD HH:MM\nНапример: 2026-10-03 18:30", "en": "Enter the start time in Tashkent local time: YYYY-MM-DD HH:MM\nExample: 2026-10-03 18:30"},
    "ask_duration": {"uz": "Umumiy vaqtni daqiqada kiriting. 0 — cheklanmagan:", "ru": "Общее время в минутах. 0 — без ограничения:", "en": "Overall time in minutes. Use 0 for no limit:"},
    "ask_chat": {"uz": "Savollar qayerda e’lon qilinsin? Guruh/kanalni tanlang yoki faqat botni tanlang.", "ru": "Где публиковать вопросы? Выберите группу/канал или только бота.", "en": "Where should questions be announced? Choose a group/channel or bot only."},
    "chat_private_only": {"uz": "Faqat bot", "ru": "Только бот", "en": "Bot only"},
    "ask_question": {"uz": "❓ {number}-bosqich uchun matn, rasm yoki videoni yuboring (izoh ixtiyoriy):", "ru": "❓ Отправьте текст, фото или видео для этапа {number} (подпись необязательна):", "en": "❓ Send the text, photo, or video for stage {number} (a caption is optional):"},
    "invalid_question": {"uz": "Savol uchun matn, rasm yoki video yuboring. Matn 4096, izoh esa 1024 belgidan oshmasin.", "ru": "Отправьте текст, фото или видео. Текст — до 4096, подпись — до 1024 символов.", "en": "Send text, a photo, or a video. Text must be at most 4096 characters; captions, 1024."},
    "invalid_correct_answer": {"uz": "To‘g‘ri javob bo‘sh bo‘lmasin va 300 belgidan oshmasin. Qayta yuboring:", "ru": "Правильный ответ не должен быть пустым и длиннее 300 символов. Отправьте ещё раз:", "en": "The correct answer must be non-empty and no longer than 300 characters. Try again:"},
    "question_archive_failed": {"uz": "Savolni arxiv kanaliga nusxalab bo‘lmadi. Bot kanal administratori ekanini va xabar joylash huquqi borligini tekshiring.", "ru": "Не удалось скопировать вопрос в архивный канал. Проверьте, что бот — администратор с правом публикации.", "en": "Could not copy the question to the archive channel. Verify the bot is an administrator with permission to post."},
    "ask_answer_mode": {"uz": "🤖 Javobni kim tekshiradi?", "ru": "🤖 Кто проверяет ответ?", "en": "🤖 Who checks the answer?"},
    "ask_correct_answer": {"uz": "✅ To‘g‘ri javobni kiriting. Harf registri hisobga olinadi:", "ru": "✅ Введите правильный ответ. Регистр букв учитывается:", "en": "✅ Enter the correct answer. Letter case matters:"},
    "ask_attempts": {"uz": "🔢 Ushbu bosqich uchun urinishlar soni (1–100):", "ru": "🔢 Число попыток для этого этапа (1–100):", "en": "🔢 Attempts allowed for this stage (1–100):"},
    "ask_stage_time": {"uz": "⏳ Bosqich vaqtini daqiqada kiriting. 0 — cheklanmagan:", "ru": "⏳ Лимит этапа в минутах. 0 — без ограничения:", "en": "⏳ Stage time limit in minutes. Use 0 for no limit:"},
    "ask_stage_start": {"uz": "📅 {number}-bosqich vaqtini Toshkent vaqti bo‘yicha kiriting: YYYY-MM-DD HH:MM\nOldingi bosqichdan keyin va umumiy muddat ichida bo‘lsin (faol kvestda kelajakdagi vaqt).", "ru": "📅 Введите время отправки этапа {number} по Ташкенту: YYYY-MM-DD HH:MM\nПозже предыдущего этапа и в пределах общего срока (для активного квеста — в будущем).", "en": "📅 Enter the delivery time for stage {number} in Tashkent time: YYYY-MM-DD HH:MM\nIt must be after the previous stage, within the quest deadline, and in the future for an active quest."},
    "stage_schedule_invalid": {"uz": "⚠️ Vaqt oldingi bosqichdan keyin va umumiy muddat ichida bo‘lishi kerak (faol kvestda — kelajakda).", "ru": "⚠️ Время должно быть позже предыдущего этапа и в пределах общего срока (для активного квеста — в будущем).", "en": "⚠️ The time must be after the previous stage, within the quest deadline, and in the future for an active quest."},
    "invalid_text": {"uz": "⚠️ Matn bo‘sh bo‘lmasin va 1 000 belgidan oshmasin. Qayta yuboring.", "ru": "⚠️ Текст не должен быть пустым и длиннее 1 000 символов. Попробуйте ещё раз.", "en": "⚠️ Text must be non-empty and no longer than 1,000 characters. Try again."},
    "invalid_number": {"uz": "⚠️ Qiymat noto‘g‘ri. Ko‘rsatilgan oraliqdagi butun sonni yuboring.", "ru": "⚠️ Некорректное значение. Отправьте целое число из указанного диапазона.", "en": "⚠️ Invalid value. Send a whole number in the stated range."},
    "invalid_datetime": {"uz": "⚠️ Sana formati noto‘g‘ri yoki vaqt oldingi bosqichdan oldin. YYYY-MM-DD HH:MM kiriting.", "ru": "⚠️ Неверный формат или время раньше предыдущего этапа. Используйте YYYY-MM-DD HH:MM.", "en": "⚠️ Invalid format or a time before the previous stage. Use YYYY-MM-DD HH:MM."},
    "created": {"uz": "✅ Kvest yaratildi: {title}\nBoshlanishi: {start}", "ru": "✅ Квест создан: {title}\nНачало: {start}", "en": "✅ Quest created: {title}\nStarts: {start}"},
    "cancelled": {"uz": "↩️ Amal bekor qilindi.", "ru": "↩️ Действие отменено.", "en": "↩️ Action cancelled."},
    "question_prefix": {"uz": "{title} — {number}-bosqich\n\n{question}\n\nUrinishlar: {attempts}{time}", "ru": "{title} — этап {number}\n\n{question}\n\nПопыток: {attempts}{time}", "en": "{title} — stage {number}\n\n{question}\n\nAttempts: {attempts}{time}"},
    "stage_meta": {"uz": "{title} — {number}-bosqich\nUrinishlar: {attempts}{time}", "ru": "{title} — этап {number}\nПопыток: {attempts}{time}", "en": "{title} — stage {number}\nAttempts: {attempts}{time}"},
    "stage_label": {"uz": "🧩 {number}-bosqich", "ru": "🧩 Этап {number}", "en": "🧩 Stage {number}"},
    "stage_attempts": {"uz": "Urinishlar", "ru": "Попыток", "en": "Attempts"},
    "quest_label_title": {"uz": "Kvest nomi", "ru": "Название квеста", "en": "Quest title"},
    "edit_quest_details_title": {"uz": "Kvest tafsilotlarini tahrirlash", "ru": "Редактирование данных квеста", "en": "Edit quest details"},
    "edit_quest_details_hint": {"uz": "Nom, tavsif va muqova rasmini o‘zgartiring. Bu ma’lumotlarni kvest yakunlangandan keyin ham, arxivlanmaguncha tahrirlash mumkin.", "ru": "Измените название, описание или обложку. Эти данные можно редактировать и после завершения квеста, пока он не архивирован.", "en": "Update the title, description, or cover photo. These details remain editable after a quest ends, until it is archived."},
    "edit_quest_cover_title": {"uz": "Kvest muqovasi", "ru": "Обложка квеста", "en": "Quest cover photo"},
    "edit_quest_cover_missing": {"uz": "📭 Hozircha muqova rasmi qo‘shilmagan.", "ru": "📭 Обложка пока не добавлена.", "en": "📭 No cover photo is set yet."},
    "edit_quest_cover_has_photo": {"uz": "✅ Muqova rasmi mavjud. Quyida joriy nusxasi ko‘rsatilgan.", "ru": "✅ Обложка добавлена. Ниже показана текущая версия.", "en": "✅ A cover photo is set. The current copy is shown below."},
    "ask_quest_title": {"uz": "Kvestning yangi nomini yuboring (1–100 belgi):", "ru": "Отправьте новое название квеста (1–100 символов):", "en": "Send the new quest title (1–100 characters):"},
    "ask_quest_description": {"uz": "Kvestning yangi tavsifini yuboring (1–1 000 belgi):", "ru": "Отправьте новое описание квеста (1–1 000 символов):", "en": "Send the new quest description (1–1,000 characters):"},
    "ask_quest_cover": {"uz": "Yangi muqova uchun rasm yuboring. Joriy rasm yangi rasm muvaffaqiyatli saqlangach almashtiriladi.", "ru": "Отправьте новое фото для обложки. Текущая обложка заменится после успешного сохранения новой.", "en": "Send a new cover photo. The current cover will be replaced only after the new photo is saved successfully."},
    "invalid_quest_title": {"uz": "Nom 1–100 belgidan iborat bo‘lishi kerak. Qayta yuboring:", "ru": "Название должно содержать от 1 до 100 символов. Попробуйте ещё раз:", "en": "The title must be 1–100 characters. Try again:"},
    "invalid_quest_description": {"uz": "Tavsif 1–1 000 belgidan iborat bo‘lishi kerak. Qayta yuboring:", "ru": "Описание должно содержать от 1 до 1 000 символов. Попробуйте ещё раз:", "en": "The description must be 1–1,000 characters. Try again:"},
    "invalid_quest_cover": {"uz": "Muqova uchun rasm yuboring yoki bekor qilish tugmasini bosing.", "ru": "Отправьте фото для обложки или нажмите «Отмена».", "en": "Send a photo for the cover or press Cancel."},
    "confirm_remove_cover": {"uz": "Ushbu kvestning muqova rasmini olib tashlaysizmi? Arxivdagi nusxasi ham o‘chiriladi.", "ru": "Удалить обложку этого квеста? Архивная копия также будет удалена.", "en": "Remove this quest’s cover photo? Its archived copy will also be deleted."},
    "quest_title_updated": {"uz": "Kvest nomi yangilandi.", "ru": "Название квеста обновлено.", "en": "Quest title updated."},
    "quest_description_updated": {"uz": "Kvest tavsifi yangilandi.", "ru": "Описание квеста обновлено.", "en": "Quest description updated."},
    "quest_cover_updated": {"uz": "Kvest muqovasi yangilandi.", "ru": "Обложка квеста обновлена.", "en": "Quest cover photo updated."},
    "quest_cover_removed": {"uz": "Kvest muqovasi olib tashlandi.", "ru": "Обложка квеста удалена.", "en": "Quest cover photo removed."},
    "quest_metadata_archived": {"uz": "⚠️ Arxivlangan kvest tafsilotlarini tahrirlab bo‘lmaydi.", "ru": "⚠️ Нельзя редактировать данные архивного квеста.", "en": "⚠️ Archived quest details cannot be edited."},
    "edit_questions_title": {"uz": "📚 Tahrirlash mumkin bo‘lgan bosqichni tanlang. Yetkazilgan savollar o‘zgarmaydi.", "ru": "📚 Выберите этап для редактирования. Уже доставленные вопросы изменить нельзя.", "en": "📚 Choose a stage to edit. Questions already delivered cannot be changed."},
    "no_editable_stages": {"uz": "📭 Hozircha tahrirlash mumkin bo‘lgan savol yo‘q.", "ru": "📭 Сейчас нет вопросов, доступных для редактирования.", "en": "📭 There are no questions available to edit right now."},
    "edit_stage_title": {"uz": "✏️ {number}-bosqichni tahrirlash:", "ru": "✏️ Редактирование этапа {number}:", "en": "✏️ Edit stage {number}:"},
    "confirm_remove_stage": {"uz": "{number}-bosqichni olib tashlaysizmi? Keyingi bosqichlar raqami avtomatik yangilanadi.", "ru": "Удалить этап {number}? Номера следующих этапов будут обновлены автоматически.", "en": "Remove stage {number}? Later stages will be renumbered automatically."},
    "stage_added": {"uz": "✅ {number}-bosqich qo‘shildi. Jami bosqichlar: {count}.", "ru": "✅ Этап {number} добавлен. Всего этапов: {count}.", "en": "✅ Stage {number} added. Total stages: {count}."},
    "stage_removed": {"uz": "✅ Bosqich olib tashlandi. Jami bosqichlar: {count}.", "ru": "✅ Этап удалён. Всего этапов: {count}.", "en": "✅ Stage removed. Total stages: {count}."},
    "stage_limit_reached": {"uz": "⚠️ Kvestda ko‘pi bilan 30 ta bosqich bo‘lishi mumkin.", "ru": "⚠️ В квесте может быть не более 30 этапов.", "en": "⚠️ A quest can have at most 30 stages."},
    "ask_replacement_question": {"uz": "✏️ Yangi matn, rasm yoki videoni yuboring. Media uchun izoh ixtiyoriy.", "ru": "✏️ Отправьте новый текст, фото или видео. Подпись к медиа необязательна.", "en": "✏️ Send the replacement text, photo, or video. A media caption is optional."},
    "ask_replacement_answer": {"uz": "✅ Yangi to‘g‘ri javobni yuboring:", "ru": "✅ Отправьте новый правильный ответ:", "en": "✅ Send the new correct answer:"},
    "stage_question_updated": {"uz": "✅ Savol yangilandi.", "ru": "✅ Вопрос обновлён.", "en": "✅ Question updated."},
    "stage_answer_updated": {"uz": "✅ To‘g‘ri javob yangilandi.", "ru": "✅ Правильный ответ обновлён.", "en": "✅ Correct answer updated."},
    "stage_not_editable": {"uz": "⚠️ Bu bosqich allaqachon yetkazilgan yoki tahrirlash uchun yopilgan.", "ru": "⚠️ Этот этап уже доставлен или закрыт для редактирования.", "en": "⚠️ This stage has already been delivered or is locked for editing."},
    "edit_cancelled": {"uz": "↩️ Tahrirlash bekor qilindi.", "ru": "↩️ Редактирование отменено.", "en": "↩️ Editing cancelled."},
    "stage_time_hint": {"uz": "\nVaqt limiti: {minutes} daqiqa", "ru": "\nЛимит времени: {minutes} мин.", "en": "\nTime limit: {minutes} minutes"},
    "send_answer": {"uz": "Javobingizni shu chatga matn qilib yuboring.", "ru": "Отправьте ответ текстовым сообщением сюда.", "en": "Send your answer as a text message here."},
    "correct_next": {"uz": "✅ To‘g‘ri javob! Keyingi bosqichga o‘tish uchun «{button}» tugmasini bosing.", "ru": "✅ Верный ответ! Нажмите «{button}», чтобы перейти к следующему этапу.", "en": "✅ Correct answer! Press “{button}” to open the next stage."},
    "correct_wait": {"uz": "✅ To‘g‘ri! Keyingi bosqich belgilangan vaqtda yuboriladi.", "ru": "✅ Верно! Следующий этап придёт по расписанию.", "en": "✅ Correct! The next stage will arrive at its scheduled time."},
    "correct_done": {"uz": "🏁 To‘g‘ri! Kvestni yakunladingiz.", "ru": "🏁 Верно! Вы завершили квест.", "en": "🏁 Correct! You completed the quest."},
    "wrong_answer": {"uz": "❌ Javob noto‘g‘ri. Qolgan urinishlar: {remaining}.", "ru": "❌ Неверный ответ. Осталось попыток: {remaining}.", "en": "❌ Incorrect answer. Attempts remaining: {remaining}."},
    "attempts_exhausted": {"uz": "❌ Urinishlar tugadi. Ushbu kvestdagi ishtirokingiz yakunlandi.", "ru": "❌ Попытки закончились. Ваше участие в квесте завершено.", "en": "❌ No attempts remain. Your participation in this quest has ended."},
    "answer_pending": {"uz": "Javob administrator tekshiruviga yuborildi.", "ru": "Ответ отправлен администратору на проверку.", "en": "Your answer was sent to the quest admin for review."},
    "no_active_question": {"uz": "Hozir javob berishingiz kerak bo‘lgan bosqich yo‘q.", "ru": "Сейчас нет открытого этапа для ответа.", "en": "There is no open stage for you to answer right now."},
    "choose_answer_quest": {"uz": "Bir nechta kvestda ochiq savolingiz bor. Javob bermoqchi bo‘lgan kvestni tanlang:", "ru": "У вас есть открытые вопросы в нескольких квестах. Выберите квест для ответа:", "en": "You have open questions in multiple quests. Choose which one to answer:"},
    "pending_admin_notice": {"uz": "Tekshirish kerak bo‘lgan javob: {user}, {title}, {stage}-bosqich.\n{answer}", "ru": "Ответ требует проверки: {user}, {title}, этап {stage}.\n{answer}", "en": "Answer needs review: {user}, {title}, stage {stage}.\n{answer}"},
    "stage_timeout": {"uz": "⏰ Bosqich vaqti tugadi. Ishtirokingiz yakunlandi.", "ru": "⏰ Время этапа истекло. Ваше участие завершено.", "en": "⏰ The stage timed out. Your participation has ended."},
    "quest_ended": {"uz": "Kvest yakunlandi.", "ru": "Квест завершён.", "en": "The quest has ended."},
    "admin_only": {"uz": "🔒 Bu amal faqat administratorlar uchun.", "ru": "🔒 Действие доступно только администраторам.", "en": "🔒 This action is available to admins only."},
    "superadmin_only": {"uz": "🔒 Bu amal faqat bosh administrator uchun.", "ru": "🔒 Действие доступно только суперадминистратору.", "en": "🔒 This action is available to the superadmin only."},
    "admin_panel": {"uz": "🛠️ Administrator paneli", "ru": "🛠️ Панель администратора", "en": "🛠️ Admin panel"},
    "stats": {"uz": "👥 Foydalanuvchilar jami: {users}\n🆕 So‘nggi 30 kunda yangi: {new_users_30d}\n🟢 Faol (7 kun): {active_users_7d}\n📅 Faol (30 kun): {active_users_30d}\n🌐 Til bo‘yicha: o‘zbekcha {language_uz}, yangi o‘zbekcha {language_uzn}, qoraqalpoqcha {language_kaa}, ruscha {language_ru}, inglizcha {language_en}\n\n🛡 Adminlar: {admins}\n🧭 Kvestlar jami: {quests}\n🟢 Faol kvestlar: {active}\n⏸️ Vaqtincha to‘xtatilgan kvestlar: {paused}\n✅ Yakunlangan kvestlar: {completed}\n👥 Qatnashuvlar: {participants} ({participating_users} foydalanuvchi)\n🏁 Yakunlangan qatnashuvlar: {completed_participations} ({participation_completion_percent}%)", "ru": "👥 Всего пользователей: {users}\n🆕 Новых за 30 дней: {new_users_30d}\n🟢 Активных за 7 дней: {active_users_7d}\n📅 Активных за 30 дней: {active_users_30d}\n🌐 Языки: узбекский {language_uz}, новый узбекский {language_uzn}, каракалпакский {language_kaa}, русский {language_ru}, английский {language_en}\n\n🛡 Администраторы: {admins}\n🧭 Всего квестов: {quests}\n🟢 Активных квестов: {active}\n⏸️ Приостановленных квестов: {paused}\n✅ Завершённых квестов: {completed}\n👥 Участий: {participants} (пользователей: {participating_users})\n🏁 Завершённых участий: {completed_participations} ({participation_completion_percent}%)", "en": "👥 Total users: {users}\n🆕 New in the last 30 days: {new_users_30d}\n🟢 Active in the last 7 days: {active_users_7d}\n📅 Active in the last 30 days: {active_users_30d}\n🌐 Languages: Uzbek {language_uz}, New Uzbek {language_uzn}, Karakalpak {language_kaa}, Russian {language_ru}, English {language_en}\n\n🛡 Admins: {admins}\n🧭 Total quests: {quests}\n🟢 Active quests: {active}\n⏸️ Paused quests: {paused}\n✅ Completed quests: {completed}\n👥 Participations: {participants} ({participating_users} users)\n🏁 Completed participations: {completed_participations} ({participation_completion_percent}%)"},
    "no_logs": {"uz": "Jurnal yozuvlari yo‘q.", "ru": "Записей журнала пока нет.", "en": "No audit entries yet."},
    "logs_title": {"uz": "📜 So‘nggi harakatlar", "ru": "📜 Последние действия", "en": "📜 Recent actions"},
    "settings_page_size": {"uz": "⚙️ Sahifadagi kvestlar soni: {size}", "ru": "⚙️ Квестов на странице: {size}", "en": "⚙️ Quests per page: {size}"},
    "choose_page_size": {"uz": "🔢 Sahifada ko‘rsatiladigan kvestlar soni:", "ru": "🔢 Количество квестов на странице:", "en": "🔢 Choose the number of quests per page:"},
    "admins_title": {"uz": "👥 Adminlar ro‘yxati", "ru": "👥 Список администраторов", "en": "👥 Administrators"},
    "ask_admin_id": {"uz": "Yangi administratorning Telegram ID raqamini yuboring:", "ru": "Отправьте Telegram ID нового администратора:", "en": "Send the new admin’s Telegram numeric ID:"},
    "admin_added": {"uz": "Administrator tayinlandi.", "ru": "Администратор назначен.", "en": "Admin appointed."},
    "admin_removed": {"uz": "Administrator huquqi olib tashlandi.", "ru": "Права администратора сняты.", "en": "Admin access removed."},
    "invalid_admin_id": {"uz": "Telegram ID musbat son bo‘lishi kerak.", "ru": "Telegram ID должен быть положительным числом.", "en": "Telegram ID must be a positive number."},
    "confirm_finish": {"uz": "Kvestni yakunlaysizmi? Ishtirokchilar javob bera olmaydi.", "ru": "Завершить квест? Участники больше не смогут отвечать.", "en": "Finish this quest? Participants will no longer be able to answer."},
    "quest_finished": {"uz": "Kvest yakunlandi.", "ru": "Квест завершён.", "en": "Quest completed."},
    "quest_archived": {"uz": "Kvest arxivlandi.", "ru": "Квест архивирован.", "en": "Quest archived."},
    "quest_unarchived": {"uz": "Kvest arxivdan chiqarildi.", "ru": "Квест восстановлен из архива.", "en": "Quest unarchived."},
    "btn_message_participant": {"uz": "✉️ Xabar yuborish", "ru": "✉️ Написать", "en": "✉️ Message"},
    "participants_title": {"uz": "Ishtirokchilar", "ru": "Участники", "en": "Participants"},
    "ask_participant_message": {"uz": "✉️ {user} ga “{title}” kvesti bo‘yicha xabar matnini yuboring (1–2 000 belgi). Bekor qilish uchun /cancel buyrug‘ini yuboring.", "ru": "✉️ Отправьте текст для участника {user} по квесту «{title}» (1–2 000 символов). Для отмены отправьте /cancel.", "en": "✉️ Send a message to {user} about the quest “{title}” (1–2,000 characters). Send /cancel to stop."},
    "participant_message_heading": {"uz": "📩 Bosh administratordan xabar · {title}", "ru": "📩 Сообщение от суперадминистратора · {title}", "en": "📩 Message from the superadmin · {title}"},
    "participant_message_sent": {"uz": "✅ Xabar {user} ga yuborildi.", "ru": "✅ Сообщение отправлено пользователю {user}.", "en": "✅ Message sent to {user}."},
    "invalid_participant_message": {"uz": "⚠️ Xabar bo‘sh bo‘lmasligi va 2 000 belgidan oshmasligi kerak.", "ru": "⚠️ Сообщение должно содержать от 1 до 2 000 символов.", "en": "⚠️ The message must contain 1–2,000 characters."},
    "participant_message_delivery_failed": {"uz": "⚠️ Xabar yetkazilmadi. Ishtirokchi botni bloklagan bo‘lishi mumkin.", "ru": "⚠️ Не удалось доставить сообщение. Возможно, участник заблокировал бота.", "en": "⚠️ Delivery failed. The participant may have blocked the bot."},
    "participant_message_unavailable": {"uz": "⚠️ Kvest ishtirokchisi topilmadi.", "ru": "⚠️ Участник квеста не найден.", "en": "⚠️ Quest participant not found."},
    "participant_message_finish_current_flow": {"uz": "Avval davom etayotgan amalni yakunlang yoki /cancel buyrug‘ini yuboring.", "ru": "Сначала завершите текущее действие или отправьте /cancel.", "en": "Finish the current action first or send /cancel."},
    "no_participants": {"uz": "Hozircha ishtirokchilar yo‘q.", "ru": "Пока нет участников.", "en": "There are no participants yet."},
    "ask_ban_reason": {"uz": "Bloklash sababini yuboring yoki tugmani bosing. Ishtirokchiga ogohlantirish yuboriladi.", "ru": "Отправьте причину блокировки или нажмите кнопку. Участник получит предупреждение.", "en": "Send a reason or press the button. The participant will be notified."},
    "blocked_success": {"uz": "Ishtirokchi bloklandi va ogohlantirildi.", "ru": "Участник заблокирован и уведомлён.", "en": "Participant blocked and notified."},
    "unblocked_success": {"uz": "Ishtirokchi blokdan chiqarildi.", "ru": "Участник разблокирован.", "en": "Participant unblocked."},
    "leaderboard_title": {"uz": "🏆 Reyting: {title}", "ru": "🏆 Рейтинг: {title}", "en": "🏆 Leaderboard: {title}"},
    "leaderboard_empty": {"uz": "Reyting uchun ma’lumot yo‘q.", "ru": "Данных для рейтинга нет.", "en": "No leaderboard data yet."},
    "leaderboard_row": {"uz": "{rank}. {name} — {solved} bosqich, {status}{completion}", "ru": "{rank}. {name} — этапов: {solved}, {status}{completion}", "en": "{rank}. {name} — {solved} stages, {status}{completion}"},
    "leaderboard_completion": {"uz": " · yakunlandi: {time}", "ru": " · время завершения: {time}", "en": " · completed: {time}"},
    "ratings_overview_title": {"uz": "Ommaviy kvestlar umumiy reytingi", "ru": "Общий рейтинг публичных квестов", "en": "Aggregate public quest leaderboard"},
    "aggregate_leaderboard_title": {"uz": "🏆 {period} reytingi", "ru": "🏆 Рейтинг: {period}", "en": "🏆 {period} leaderboard"},
    "aggregate_leaderboard_row": {"uz": "{rank}. {name} — {points} ball, {completed} ta kvest yakunlangan", "ru": "{rank}. {name} — {points} очк., завершено квестов: {completed}", "en": "{rank}. {name} — {points} points, {completed} quests completed"},
    "aggregate_leaderboard_empty": {"uz": "Bu davrda natijalar yo‘q.", "ru": "За этот период результатов пока нет.", "en": "No results for this period yet."},
    "role_admin": {"uz": "Administrator", "ru": "Админ", "en": "Admin"},
    "role_superadmin": {"uz": "Bosh administrator", "ru": "Суперадмин", "en": "Superadmin"},
    "participant_joined": {"uz": "🟡 qo‘shilgan", "ru": "🟡 присоединился", "en": "🟡 joined"},
    "participant_active": {"uz": "🟢 qatnashmoqda", "ru": "🟢 участвует", "en": "🟢 active"},
    "participant_completed": {"uz": "✅ yakunlagan", "ru": "✅ завершил", "en": "✅ completed"},
    "participant_failed": {"uz": "❌ urinish tugagan", "ru": "❌ попытки исчерпаны", "en": "❌ out of attempts"},
    "participant_blocked": {"uz": "🚫 bloklangan", "ru": "🚫 заблокирован", "en": "🚫 blocked"},
    "support_choose": {"uz": "Kimga murojaat qilmoqchisiz?", "ru": "Кому вы хотите написать?", "en": "Who would you like to contact?"},
    "support_no_quests": {"uz": "Kvest adminiga yozish uchun qatnashgan kvestingiz yo‘q.", "ru": "Нет квестов, в которых вы участвовали.", "en": "You have no participating quests to contact an admin about."},
    "support_ask": {"uz": "Xabaringizni yuboring. Bekor qilish uchun /cancel.", "ru": "Отправьте сообщение. Для отмены — /cancel.", "en": "Send your message. Use /cancel to stop."},
    "support_created": {"uz": "Murojaatingiz yuborildi. Javob bot orqali keladi.", "ru": "Обращение отправлено. Ответ придёт через бота.", "en": "Your support message was sent. Replies arrive through the bot."},
    "support_notification": {"uz": "Yangi murojaat #{ticket} (foydalanuvchi {user}):\n{message}", "ru": "Новое обращение #{ticket} (пользователь {user}):\n{message}", "en": "New support ticket #{ticket} (user {user}):\n{message}"},
    "support_reply_prompt": {"uz": "#{ticket} murojaatiga javob yuboring:", "ru": "Отправьте ответ на обращение #{ticket}:", "en": "Send your reply to ticket #{ticket}:"},
    "support_you": {"uz": "Siz", "ru": "Вы", "en": "You"},
    "support_admin_reply_sent": {"uz": "Javob yuborildi.", "ru": "Ответ отправлен.", "en": "Reply sent."},
    "support_reply_to_user": {"uz": "#{ticket} murojaati · {source}:\n{message}", "ru": "Обращение #{ticket} · {source}:\n{message}", "en": "Ticket #{ticket} · {source}:\n{message}"},
    "support_source_quest_admin": {"uz": "«{quest}» kvesti administratori", "ru": "Администратор квеста «{quest}»", "en": "Quest admin for “{quest}”"},
    "support_source_superadmin": {"uz": "Bosh administrator", "ru": "Суперадминистратор", "en": "Superadmin"},
    "support_thread_notification": {"uz": "#{ticket} murojaati · {source}\nFoydalanuvchi: {user}\n{message}", "ru": "Обращение #{ticket} · {source}\nПользователь: {user}\n{message}", "en": "Ticket #{ticket} · {source}\nUser: {user}\n{message}"},
    "support_history_line": {"uz": "{sender}: {message}", "ru": "{sender}: {message}", "en": "{sender}: {message}"},
    "support_reply_to_admin": {"uz": "#{ticket} murojaatiga yangi xabar:\n{message}", "ru": "Новое сообщение в обращении #{ticket}:\n{message}", "en": "New message in ticket #{ticket}:\n{message}"},
    "no_tickets": {"uz": "Murojaatlaringiz yo‘q.", "ru": "У вас нет обращений.", "en": "You have no support tickets."},
    "ticket_history": {"uz": "Murojaat #{ticket} ({status}):\n{messages}", "ru": "Обращение #{ticket} ({status}):\n{messages}", "en": "Ticket #{ticket} ({status}):\n{messages}"},
    "ticket_open": {"uz": "📬 ochiq", "ru": "📬 открыто", "en": "📬 open"},
    "ticket_closed": {"uz": "✅ yopiq", "ru": "✅ закрыто", "en": "✅ closed"},
    "admin_review_title": {"uz": "Tekshiruvdagi javoblar", "ru": "Ответы на проверке", "en": "Answers awaiting review"},
    "no_pending": {"uz": "Tekshiriladigan javob yo‘q.", "ru": "Нет ответов на проверке.", "en": "No answers are waiting for review."},
    "review_item": {"uz": "{name}, {stage}-bosqich:\n{answer}", "ru": "{name}, этап {stage}:\n{answer}", "en": "{name}, stage {stage}:\n{answer}"},
    "review_approved": {"uz": "Javob to‘g‘ri deb tasdiqlandi.", "ru": "Ответ принят как верный.", "en": "Answer approved as correct."},
    "review_rejected": {"uz": "Javob noto‘g‘ri deb belgilandi.", "ru": "Ответ отмечен как неверный.", "en": "Answer rejected as incorrect."},
    "review_to_user": {"uz": "Kvest administratori javobingizni {result} deb belgiladi.", "ru": "Администратор отметил ваш ответ как {result}.", "en": "The quest admin marked your answer {result}."},
    "correct_result": {"uz": "to‘g‘ri", "ru": "верным", "en": "correct"},
    "wrong_result": {"uz": "noto‘g‘ri", "ru": "неверным", "en": "incorrect"},
    "ask_chat_id": {"uz": "Guruh/kanal chat ID raqamini yuboring. Bot shu chatda administrator bo‘lishi kerak; ID olish uchun guruhda /chatid buyrug‘idan foydalaning.", "ru": "Отправьте chat ID группы/канала. Бот должен быть администратором; чтобы узнать ID, используйте /chatid в чате.", "en": "Send the group/channel chat ID. The bot must be an admin there; use /chatid in that chat to find the ID."},
    "chat_added": {"uz": "Guruh yoki kanal ro‘yxatga qo‘shildi: {title}", "ru": "Чат добавлен: {title}", "en": "Chat registered: {title}"},
    "chat_not_found": {"uz": "Guruh yoki kanal topilmadi yoxud botda kerakli administrator huquqlari yo‘q.", "ru": "Чат не найден или у бота нет необходимых прав администратора.", "en": "Chat not found or the bot lacks required administrator rights."},
    "chat_permission_missing": {"uz": "Botga kanalda xabar yuborish yoki a’zolarni cheklash uchun kerakli administrator huquqini bering.", "ru": "Дайте боту право публиковать сообщения в канале или ограничивать участников.", "en": "Grant the bot permission to post in the channel or restrict chat members."},
    "chats_empty": {"uz": "Ro‘yxatga olingan guruh/kanal yo‘q.", "ru": "Нет зарегистрированных групп/каналов.", "en": "No groups/channels are registered."},
    "chat_info": {"uz": "{title}\nID: {chat_id}\nBoshlanishda a’zolarni chiqarish: {cleanup}", "ru": "{title}\nID: {chat_id}\nУдалять участников при старте: {cleanup}", "en": "{title}\nID: {chat_id}\nRemove known members at start: {cleanup}"},
    "cleanup_on": {"uz": "yoqilgan", "ru": "включено", "en": "enabled"},
    "cleanup_off": {"uz": "o‘chirilgan", "ru": "выключено", "en": "disabled"},
    "whitelist_title": {"uz": "Chiqarishdan mustasno foydalanuvchilar ID raqamlari", "ru": "Исключённые из удаления user ID", "en": "User IDs excluded from removal"},
    "ask_whitelist_id": {"uz": "Chiqarilmaydigan foydalanuvchining Telegram ID raqamini yuboring:", "ru": "Отправьте Telegram ID пользователя, которого нельзя удалять:", "en": "Send the Telegram ID of a user to exclude from removal:"},
    "whitelist_added": {"uz": "Istisno ro‘yxatiga qo‘shildi.", "ru": "Добавлено в список исключений.", "en": "Added to the exclusion list."},
    "whitelist_removed": {"uz": "Istisno ro‘yxatidan olindi.", "ru": "Удалено из списка исключений.", "en": "Removed from the exclusion list."},
    "no_whitelist": {"uz": "Istisnolar yo‘q.", "ru": "Исключений нет.", "en": "No exclusions."},
    "invite_link_ready": {"uz": "Chatga kirish uchun bir kishilik, muddatsiz havola:\n{link}\nHavolani olgan odam bilan shaxsiy ulashing.", "ru": "Одноразовая бессрочная ссылка в чат:\n{link}\nПередавайте её адресно.", "en": "One-person, non-expiring chat invite:\n{link}\nShare it privately with the intended person."},
    "invite_unavailable": {"uz": "Chatga havola yaratib bo‘lmadi. Botda taklif havolasi yaratish huquqi bo‘lishi kerak.", "ru": "Не удалось создать ссылку. Боту нужно право приглашать участников.", "en": "Could not create the invite. The bot needs permission to invite members."},
    "invite_at_start": {"uz": "Chatga kirish uchun havola kvest boshlanganda yuboriladi.", "ru": "Ссылка для входа в чат придёт после начала квеста.", "en": "The chat invite link will be sent when the quest starts."},
    "service_started": {
        "uz": "✅ Quest Bot ishga tushdi.",
        "ru": "✅ Quest Bot запущен.",
        "en": "✅ Quest Bot has started.",
    },
    "service_stopping": {
        "uz": "⏹️ Quest Bot to‘xtatilmoqda. Ma’lumotlar bazasi zaxira nusxasi tayyorlanmoqda.",
        "ru": "⏹️ Quest Bot останавливается. Создаётся резервная копия базы данных.",
        "en": "⏹️ Quest Bot is stopping. A database backup is being prepared.",
    },
    "database_backup_caption": {
        "uz": "Quest Bot ma’lumotlar bazasi zaxira nusxasi ({timestamp} UTC).",
        "ru": "Резервная копия базы Quest Bot ({timestamp} UTC).",
        "en": "Quest Bot database backup ({timestamp} UTC).",
    },
    "database_backup_failed": {
        "uz": "Ma’lumotlar bazasi zaxira nusxasini yaratib bo‘lmadi. Server jurnalini tekshiring.",
        "ru": "Не удалось создать резервную копию базы данных. Проверьте журнал сервера.",
        "en": "The database backup could not be created. Check the server logs.",
    },
    "database_backup_delivery_failed": {
        "uz": "Zaxira faylini yuborib bo‘lmadi. Server jurnalini tekshiring.",
        "ru": "Не удалось отправить файл резервной копии. Проверьте журнал сервера.",
        "en": "The backup file could not be delivered. Check the server logs.",
    },
    "btn_start_quest": {"uz": "▶️ Kvestni boshlash", "ru": "▶️ Начать квест", "en": "▶️ Start quest"},
    "btn_continue_quest": {"uz": "⏩ Davom etish", "ru": "⏩ Продолжить", "en": "⏩ Continue"},
    "quest_started_notice": {"uz": "🚀 «{title}» kvesti boshlandi!", "ru": "🚀 Квест «{title}» начался!", "en": "🚀 “{title}” has started!"},
    "quest_started_hint": {"uz": "Tayyor bo‘lganingizda «{button}» tugmasini bosing — savol shundan keyin yuboriladi.", "ru": "Когда будете готовы, нажмите «{button}» — вопрос придёт после этого.", "en": "Press “{button}” when you are ready — the question arrives afterwards."},
    "quest_started_waiting": {"uz": "Birinchi bosqich o‘z vaqtida boshlanadi; tayyor bo‘lganda xabar beramiz.", "ru": "Первый этап начнётся по расписанию; мы сообщим, когда он будет готов.", "en": "The first stage starts on schedule; we will notify you when it is ready."},
    "stage_available_notice": {"uz": "🔔 «{title}» kvestida {number}-bosqich tayyor!", "ru": "🔔 В квесте «{title}» готов этап {number}!", "en": "🔔 Stage {number} is ready in “{title}”!"},
    "stage_continue_hint": {"uz": "Savolni olish uchun «{button}» tugmasini bosing.", "ru": "Нажмите «{button}», чтобы получить вопрос.", "en": "Press “{button}” to get the question."},
    "stage_not_started_yet": {"uz": "Keyingi bosqich hali boshlanmadi. Boshlanish vaqtini kuting.", "ru": "Следующий этап ещё не начался. Дождитесь времени начала.", "en": "The next stage has not started yet. Please wait for its start time."},
    "quest_stage_unavailable": {"uz": "Hozircha siz uchun ochiq savol yo‘q.", "ru": "Сейчас для вас нет открытого вопроса.", "en": "You have no open question right now."},
    "btn_edit_start": {"uz": "🕒 Boshlanish vaqtini tahrirlash", "ru": "🕒 Изменить время начала", "en": "🕒 Edit start time"},
    "ask_quest_start": {"uz": "Yangi boshlanish vaqtini Toshkent vaqti bo‘yicha yuboring: YYYY-MM-DD HH:MM\nMasalan: 2026-10-03 18:30", "ru": "Отправьте новое время начала по Ташкенту: YYYY-MM-DD HH:MM\nНапример: 2026-10-03 18:30", "en": "Send the new start time in Tashkent local time: YYYY-MM-DD HH:MM\nExample: 2026-10-03 18:30"},
    "quest_start_edit_hint": {"uz": "Joriy vaqt: {current}\nRejalashtirilgan bosqichlar vaqti yangi boshlanish vaqtiga mos ravishda suriladi.", "ru": "Текущее время: {current}\nВремя запланированных этапов сдвинется вместе с новым началом.", "en": "Current time: {current}\nScheduled stage times shift together with the new start time."},
    "invalid_quest_start": {"uz": "⚠️ Sana formati noto‘g‘ri yoki vaqt o‘tib ketgan.", "ru": "⚠️ Неверный формат даты или время уже прошло.", "en": "⚠️ Invalid date format or the time has already passed."},
    "quest_start_updated": {"uz": "✅ Kvest boshlanish vaqti yangilandi.", "ru": "✅ Время начала квеста обновлено.", "en": "✅ Quest start time updated."},
    "quest_start_edit_closed": {"uz": "⚠️ Boshlanish vaqtini faqat hali boshlanmagan (rejalashtirilgan) kvestda o‘zgartirish mumkin.", "ru": "⚠️ Время начала можно менять только у ещё не начавшегося (запланированного) квеста.", "en": "⚠️ The start time can be changed only while the quest has not started yet."},
    "btn_delete_quest": {"uz": "🗑️ Kvestni o‘chirish", "ru": "🗑️ Удалить квест", "en": "🗑️ Delete quest"},
    "btn_confirm_delete_quest": {"uz": "🗑️ Ha, o‘chirish", "ru": "🗑️ Да, удалить", "en": "🗑️ Yes, delete it"},
    "confirm_delete_quest": {"uz": "«{title}» kvestini o‘chirasizmi?\nKvest faqat o‘chirilgan deb belgilanadi (delete = true) va ro‘yxatlardan yashiriladi; ma’lumotlar bazadan o‘chirilmaydi.", "ru": "Удалить квест «{title}»?\nКвест будет только помечен удалённым (delete = true) и скрыт из списков; данные из базы не удаляются.", "en": "Delete “{title}”?\nThe quest is only marked as deleted (delete = true) and hidden from lists; its data stays in the database."},
    "quest_deleted": {"uz": "🗑️ Kvest o‘chirilgan deb belgilandi (delete = true). Ma’lumotlar bazada saqlanadi; uni faqat bosh administrator ko‘ra oladi va tiklay oladi.", "ru": "🗑️ Квест помечен удалённым (delete = true). Данные остались в базе; видеть и восстановить его может только суперадминистратор.", "en": "🗑️ The quest is marked as deleted (delete = true). Its data remains in the database, and only the superadmin can see and restore it."},
    "btn_restore_quest": {"uz": "♻️ Kvestni tiklash", "ru": "♻️ Восстановить квест", "en": "♻️ Restore quest"},
    "quest_restored": {"uz": "♻️ Kvest tiklandi va ro‘yxatlarda yana ko‘rinadi.", "ru": "♻️ Квест восстановлен и снова виден в списках.", "en": "♻️ The quest was restored and is visible in lists again."},
    "filter_deleted": {"uz": "🗑 O‘chirilganlar", "ru": "🗑 Удалённые", "en": "🗑 Deleted"},
    "deleted_quest_view_title": {"uz": "🗑 O‘chirilgan kvest", "ru": "🗑 Удалённый квест", "en": "🗑 Deleted quest"},
    "deleted_quest_view_body": {"uz": "Bu kvest o‘chirilgan deb belgilangan (delete = true), shuning uchun foydalanuvchilarga ko‘rinmaydi. Ma’lumotlar bazada saqlanmoqda.", "ru": "Этот квест помечен удалённым (delete = true), поэтому пользователи его не видят. Данные хранятся в базе.", "en": "This quest is marked as deleted (delete = true), so users cannot see it. Its data is preserved in the database."},
    "ask_attempts_mode": {"uz": "Barcha bosqichlar uchun urinishlar soni bir xilmi yoki har xilmi?", "ru": "Число попыток одинаково для всех этапов или разное?", "en": "Is the attempt limit the same for every stage or different?"},
    "attempts_same": {"uz": "🔁 Bir xil (hammasi uchun bitta son)", "ru": "🔁 Одинаковое (одно число для всех)", "en": "🔁 Same for all stages"},
    "attempts_different": {"uz": "🔢 Har xil (har bir bosqich uchun alohida)", "ru": "🔢 Разное (для каждого этапа отдельно)", "en": "🔢 Different for each stage"},
    "ask_common_attempts": {"uz": "Barcha bosqichlar uchun urinishlar sonini kiriting (1–100):", "ru": "Введите число попыток для всех этапов (1–100):", "en": "Send the attempt limit used by every stage (1–100):"},
    "ambiguous_message_title": {"uz": "❓ Bu javobmi yoki murojaatmi?", "ru": "❓ Это ответ или обращение?", "en": "❓ Is this an answer or a support message?"},
    "ambiguous_message_body": {"uz": "Sizda javob kutilayotgan kvest bosqichi bor. Yuborgan matningizni qanday qabul qilishimni tanlang:", "ru": "У вас есть этап квеста, ожидающий ответа. Выберите, как обработать отправленный текст:", "en": "You have a quest stage waiting for an answer. Choose how to treat the text you just sent:"},
    "btn_pending_as_answer": {"uz": "🎯 «{title}» kvestiga javob", "ru": "🎯 Ответ на квест «{title}»", "en": "🎯 Answer for “{title}”"},
    "btn_pending_as_ticket": {"uz": "💬 Murojaat sifatida yuborish", "ru": "💬 Отправить как обращение", "en": "💬 Send as a support message"},
    "participant_message_heading_admin": {"uz": "📩 Kvest administratoridan xabar · {title}", "ru": "📩 Сообщение от администратора квеста · {title}", "en": "📩 Message from the quest administrator · {title}"},
    "error_generic": {"uz": "Xatolik yuz berdi. Qayta urinib ko‘ring.", "ru": "Произошла ошибка. Попробуйте ещё раз.", "en": "Something went wrong. Please try again."},
    "btn_open_quest": {"uz": "🧭 Kvestni ochish", "ru": "🧭 Открыть квест", "en": "🧭 Open quest"},
    "invalid_quest_start_min": {"uz": "⚠️ Boshlanish vaqti hozirdan kamida 10 daqiqa keyin bo‘lishi kerak.", "ru": "⚠️ Время начала должно быть не раньше, чем через 10 минут.", "en": "⚠️ The start time must be at least 10 minutes from now."},
    "btn_purge_quest": {"uz": "🧨 Butunlay o‘chirish", "ru": "🧨 Удалить навсегда", "en": "🧨 Delete permanently"},
    "btn_confirm_purge_quest": {"uz": "🧨 Ha, butunlay o‘chirish", "ru": "🧨 Да, удалить навсегда", "en": "🧨 Yes, delete permanently"},
    "confirm_purge_quest": {"uz": "🧨 «{title}» butunlay o‘chiriladi: kvest, savollar, ishtirokchilar va javoblar bazadan o‘chib ketadi. Bu amalni qaytarib bo‘lmaydi.", "ru": "🧨 «{title}» будет удалён навсегда: квест, вопросы, участники и ответы исчезнут из базы. Отменить это действие нельзя.", "en": "🧨 “{title}” will be deleted permanently: the quest, its questions, participants, and answers are removed from the database. This cannot be undone."},
    "quest_purged": {"uz": "🧨 «{title}» butunlay o‘chirildi.", "ru": "🧨 «{title}» полностью удалён.", "en": "🧨 “{title}” was permanently deleted."},
    "deleted_quest_purge_hint": {"uz": "Agar bu kvest umuman kerak bo‘lmasa, uni bazadan butunlay o‘chirish mumkin.", "ru": "Если квест больше не нужен, его можно удалить из базы навсегда.", "en": "If this quest is not needed at all, it can be removed from the database permanently."},
    "admin_detail_title": {"uz": "👤 Administrator: {name}", "ru": "👤 Администратор: {name}", "en": "👤 Administrator: {name}"},
    "admin_detail_body": {"uz": "{role} · ID: {user_id}\n🧭 Kvestlari: {quests} · 🗑 O‘chirilganlari: {deleted}", "ru": "{role} · ID: {user_id}\n🧭 Квестов: {quests} · 🗑 Удалённых: {deleted}", "en": "{role} · ID: {user_id}\n🧭 Quests: {quests} · 🗑 Deleted: {deleted}"},
    "btn_admin_quests": {"uz": "🧭 Kvestlarini ko‘rish", "ru": "🧭 Его квесты", "en": "🧭 Their quests"},
    "btn_message_admin": {"uz": "✉️ Xabar yuborish", "ru": "✉️ Написать", "en": "✉️ Send message"},
    "admin_quests_title": {"uz": "🧭 {name} kvestlari", "ru": "🧭 Квесты: {name}", "en": "🧭 Quests of {name}"},
    "admin_quests_empty": {"uz": "Bu administratorning kvestlari yo‘q.", "ru": "У этого администратора нет квестов.", "en": "This administrator has no quests."},
    "ask_admin_message": {"uz": "✉️ {name} ga yuboriladigan xabarni yozing (1–2000 belgi):", "ru": "✉️ Напишите сообщение для {name} (1–2000 символов):", "en": "✉️ Write the message to send to {name} (1–2,000 characters):"},
    "admin_message_sent": {"uz": "✅ Xabar {name} ga yuborildi.", "ru": "✅ Сообщение отправлено: {name}.", "en": "✅ Message sent to {name}."},
    "admin_message_heading": {"uz": "📩 Bosh administrator xabari", "ru": "📩 Сообщение от суперадминистратора", "en": "📩 Message from the superadmin"},
    "logs_terminal_hint": {"uz": "🖥 Oxirgi {count} yozuv · yangilash uchun «{button}» tugmasini bosing.", "ru": "🖥 Последние {count} записей · нажмите «{button}», чтобы обновить.", "en": "🖥 Last {count} entries · press “{button}” to refresh."},
    "btn_refresh": {"uz": "🔄 Yangilash", "ru": "🔄 Обновить", "en": "🔄 Refresh"},
    "no_admins": {"uz": "📭 Administratorlar yo‘q.", "ru": "📭 Администраторов пока нет.", "en": "📭 No administrators yet."},
}


def tr(language: str | None, key: str, **values: object) -> str:
    """Translate and format a message, falling back to Uzbek for unknown languages."""
    lang = language if language in LANGUAGES else "uz"
    text = TEXTS.get(key, {}).get(lang) or TEXTS.get(key, {}).get("en") or key
    try:
        return text.format(**values)
    except KeyError:
        return text


_LETTER_SUBSTITUTIONS = (
    ("O‘", "Ö"),
    ("o‘", "ö"),
    ("G‘", "Ğ"),
    ("g‘", "ğ"),
    ("SH", "Ş"),
    ("Sh", "Ş"),
    ("sh", "ş"),
    ("CH", "Ç"),
    ("Ch", "Ç"),
    ("ch", "ç"),
)

# {chat} and {chat_id} are format placeholders, not prose: translating the "ch"
# inside them would break tr()'s formatting, so they are copied unchanged.
_PLACEHOLDER = re.compile(r"\{[^{}]*\}")


def yangi_uzbek(text: str) -> str:
    """Rewrite Uzbek text with the four letters of «Yangi o‘zbek».

    Only o‘→ö, g‘→ğ, sh→ş, and ch→ç (both letter cases) change; every other
    character, including punctuation and {placeholders}, is untouched.
    """
    parts = _PLACEHOLDER.split(text)
    placeholders = _PLACEHOLDER.findall(text)
    result: list[str] = []
    for index, part in enumerate(parts):
        for source, target in _LETTER_SUBSTITUTIONS:
            part = part.replace(source, target)
        result.append(part)
        if index < len(placeholders):
            result.append(placeholders[index])
    return "".join(result)


# Both extra languages are derived from the base dictionaries, so they always
# cover exactly the same keys as Uzbek, Russian, and English.
for _key, _translations in TEXTS.items():
    _translations["uzn"] = yangi_uzbek(_translations["uz"])
    _translations["kaa"] = KARAKALPAK_TEXTS[_key]
