"""Translated user-facing messages for Uzbek, Russian, and English."""

from __future__ import annotations

LANGUAGES = ("uz", "ru", "en")
LANGUAGE_NAMES = {"uz": "O‘zbekcha", "ru": "Русский", "en": "English"}

TEXTS: dict[str, dict[str, str]] = {
    "welcome": {
        "uz": "Quest Bot’ga xush kelibsiz! Kvestlarni toping, qatnashing yoki o‘zingiz yarating.",
        "ru": "Добро пожаловать в Quest Bot! Находите квесты, участвуйте или создавайте свои.",
        "en": "Welcome to Quest Bot! Discover quests, participate, or create your own.",
    },
    "menu": {"uz": "Asosiy menyu", "ru": "Главное меню", "en": "Main menu"},
    "btn_quests": {"uz": "Kvestlarni ko‘rish", "ru": "Список квестов", "en": "Browse quests"},
    "btn_my_quests": {"uz": "Mening kvestlarim", "ru": "Мои квесты", "en": "My quests"},
    "btn_admin": {"uz": "Admin paneli", "ru": "Панель администратора", "en": "Admin panel"},
    "btn_ratings": {"uz": "Reytinglar", "ru": "Рейтинги", "en": "Leaderboards"},
    "btn_guide": {"uz": "Yo‘riqnoma", "ru": "Инструкция", "en": "How to use"},
    "btn_support": {"uz": "Yordam / murojaat", "ru": "Поддержка", "en": "Support"},
    "btn_language": {"uz": "Tilni tanlash", "ru": "Выбрать язык", "en": "Choose language"},
    "btn_back": {"uz": "⬅️ Orqaga", "ru": "⬅️ Назад", "en": "⬅️ Back"},
    "btn_home": {"uz": "🏠 Bosh menyu", "ru": "🏠 Главное меню", "en": "🏠 Main menu"},
    "btn_cancel": {"uz": "Bekor qilish", "ru": "Отмена", "en": "Cancel"},
    "btn_confirm": {"uz": "Tasdiqlash", "ru": "Подтвердить", "en": "Confirm"},
    "btn_join": {"uz": "✅ Qatnashish", "ru": "✅ Участвовать", "en": "✅ Join"},
    "btn_private_link": {"uz": "Kvest taklif havolasini olish", "ru": "Получить ссылку на квест", "en": "Get private quest link"},
    "btn_open": {"uz": "Ko‘rish", "ru": "Открыть", "en": "Open"},
    "btn_create": {"uz": "➕ Kvest yaratish", "ru": "➕ Создать квест", "en": "➕ Create quest"},
    "btn_manage": {"uz": "⚙️ Boshqarish", "ru": "⚙️ Управление", "en": "⚙️ Manage"},
    "btn_rank": {"uz": "🏆 Reyting", "ru": "🏆 Рейтинг", "en": "🏆 Leaderboard"},
    "btn_participants": {"uz": "Ishtirokchilar", "ru": "Участники", "en": "Participants"},
    "btn_pending": {"uz": "Tekshiruvdagi javoblar", "ru": "Ответы на проверке", "en": "Pending answers"},
    "btn_invite": {"uz": "Chatga bir kishilik havola", "ru": "Одноразовая ссылка в чат", "en": "One-person chat invite"},
    "btn_finish": {"uz": "Kvestni yakunlash", "ru": "Завершить квест", "en": "Finish quest"},
    "btn_archive": {"uz": "Arxivlash", "ru": "Архивировать", "en": "Archive"},
    "btn_unarchive": {"uz": "Arxivdan chiqarish", "ru": "Убрать из архива", "en": "Unarchive"},
    "btn_ban": {"uz": "🚫 Bloklash", "ru": "🚫 Заблокировать", "en": "🚫 Block"},
    "btn_unban": {"uz": "✅ Blokdan chiqarish", "ru": "✅ Разблокировать", "en": "✅ Unblock"},
    "btn_approve": {"uz": "✅ To‘g‘ri", "ru": "✅ Верно", "en": "✅ Approve"},
    "btn_reject": {"uz": "❌ Noto‘g‘ri", "ru": "❌ Неверно", "en": "❌ Reject"},
    "btn_skip": {"uz": "Sababsiz davom etish", "ru": "Без причины", "en": "Skip reason"},
    "btn_add": {"uz": "➕ Qo‘shish", "ru": "➕ Добавить", "en": "➕ Add"},
    "btn_remove": {"uz": "Olib tashlash", "ru": "Удалить", "en": "Remove"},
    "btn_toggle_cleanup": {"uz": "Chiqarish sozlamasini o‘zgartirish", "ru": "Изменить очистку участников", "en": "Toggle member cleanup"},
    "btn_whitelist": {"uz": "Istisnolar ro‘yxati", "ru": "Список исключений", "en": "Whitelist"},
    "btn_admins": {"uz": "Adminlarni boshqarish", "ru": "Администраторы", "en": "Manage admins"},
    "btn_stats": {"uz": "Statistika", "ru": "Статистика", "en": "Statistics"},
    "btn_logs": {"uz": "Harakatlar jurnali", "ru": "Журнал действий", "en": "Audit log"},
    "btn_settings": {"uz": "Sozlamalar", "ru": "Настройки", "en": "Settings"},
    "btn_export": {"uz": "Ma’lumotlarni eksport qilish", "ru": "Экспорт данных", "en": "Export data"},
    "btn_chats": {"uz": "Guruh/kanallar", "ru": "Группы/каналы", "en": "Groups/channels"},
    "btn_support_super": {"uz": "Superadminga yozish", "ru": "Написать суперадминистратору", "en": "Contact superadmin"},
    "btn_support_quest": {"uz": "Kvest adminiga yozish", "ru": "Написать админу квеста", "en": "Contact quest admin"},
    "btn_my_tickets": {"uz": "Mening murojaatlarim", "ru": "Мои обращения", "en": "My tickets"},
    "btn_reply": {"uz": "Javob yozish", "ru": "Ответить", "en": "Reply"},
    "btn_reply_ticket": {"uz": "Javob berish", "ru": "Ответить", "en": "Reply"},
    "open_private_chat": {"uz": "Davom etish uchun botni shaxsiy chatda oching.", "ru": "Чтобы продолжить, откройте бота в личном чате.", "en": "Open the bot in a private chat to continue."},
    "chat_id_result": {"uz": "Chat ID: {chat_id}\nNomi: {title}", "ru": "Chat ID: {chat_id}\nНазвание: {title}", "en": "Chat ID: {chat_id}\nTitle: {title}"},
    "welcome_hint": {
        "uz": "Tilni almashtirish uchun /language buyrug‘idan foydalaning.",
        "ru": "Чтобы сменить язык, используйте команду /language.",
        "en": "Use /language to change the interface language.",
    },
    "guide": {
        "uz": "Yo‘riqnoma:\n1. “Kvestlarni ko‘rish” orqali public kvestlarni toping. Private kvest botning taklif havolasi orqali ochiladi.\n2. Kvestga qo‘shilgach, savollar botning shaxsiy chatiga ham keladi. Kvestga biriktirilgan guruh/kanal bo‘lsa, e’lonlar u yerda chiqadi; javoblar botga private yuboriladi.\n3. Javob saqlangan javob bilan aynan solishtiriladi; bosh/oxiridagi bo‘sh joylar olib tashlanadi, katta-kichik harf farqi saqlanadi. Admin tekshiradigan bosqichlarda natijani admin belgilaydi.\n4. Reytingni kvest sahifasidan yoki “Reytinglar”dan kuzating.\n5. Yordam orqali superadmin yoki tegishli kvest adminiga yozing.\n\nAdmin o‘z kvestini yaratadi/boshqaradi. Superadmin adminlar, barcha kvestlar, arxiv, statistika, loglar va sozlamalarni boshqaradi. Botda reklama yo‘q.",
        "ru": "Инструкция:\n1. Ищите публичные квесты в «Список квестов». Приватный квест открывается по ссылке-приглашению бота.\n2. После вступления вопросы приходят также в личный чат с ботом. Если квест привязан к группе/каналу, объявления публикуются там; ответы отправляются боту в личку.\n3. Ответ сравнивается с эталоном точно; крайние пробелы удаляются, регистр учитывается. На этапах с ручной проверкой результат выставляет администратор.\n4. Рейтинг доступен на странице квеста и в разделе «Рейтинги».\n5. Через поддержку можно написать суперадминистратору или админу квеста.\n\nАдминистратор создаёт и ведёт свои квесты. Суперадминистратор управляет всеми квестами, администраторами, архивом, статистикой, журналом и настройками. Рекламы нет.",
        "en": "Guide:\n1. Find public quests in “Browse quests”. Private quests open through the bot’s invitation link.\n2. After joining, questions are also delivered in the bot’s private chat. If a group/channel is attached, announcements appear there; answers are sent privately to the bot.\n3. Answers are compared exactly with the stored answer; leading/trailing whitespace is trimmed and letter case matters. Stages with manual checking are reviewed by an admin.\n4. View rankings on the quest page or in “Leaderboards”.\n5. Use Support to contact the superadmin or the relevant quest admin.\n\nAdmins create and run their own quests. The superadmin controls all quests, admins, archives, statistics, logs, and settings. No advertising is included.",
    },
    "language_choose": {"uz": "Interfeys tilini tanlang:", "ru": "Выберите язык интерфейса:", "en": "Choose your interface language:"},
    "language_saved": {"uz": "Til O‘zbekcha qilib saqlandi.", "ru": "Язык сохранён: русский.", "en": "Language saved: English."},
    "language_button": {"uz": "O‘zbekcha", "ru": "O‘zbekcha", "en": "O‘zbekcha"},
    "quests_title": {"uz": "Ommaviy kvestlar", "ru": "Публичные квесты", "en": "Public quests"},
    "my_quests_title": {"uz": "Boshqariladigan kvestlar", "ru": "Управляемые квесты", "en": "Quests you manage"},
    "empty_quests": {"uz": "Bu bo‘limda kvest topilmadi.", "ru": "В этом разделе квестов нет.", "en": "No quests found in this section."},
    "filter_all": {"uz": "Barchasi", "ru": "Все", "en": "All"},
    "filter_scheduled": {"uz": "Kutilmoqda", "ru": "Ожидают начала", "en": "Upcoming"},
    "filter_active": {"uz": "Davom etmoqda", "ru": "Идут", "en": "Ongoing"},
    "filter_completed": {"uz": "Yakunlangan", "ru": "Завершены", "en": "Completed"},
    "filter_archived": {"uz": "Arxivlangan", "ru": "В архиве", "en": "Archived"},
    "status_scheduled": {"uz": "Kutilmoqda", "ru": "Ожидает", "en": "Upcoming"},
    "status_active": {"uz": "Davom etmoqda", "ru": "Идёт", "en": "Ongoing"},
    "status_completed": {"uz": "Yakunlangan", "ru": "Завершён", "en": "Completed"},
    "status_archived": {"uz": "Arxivlangan", "ru": "В архиве", "en": "Archived"},
    "visibility_public": {"uz": "Ommaviy", "ru": "Публичный", "en": "Public"},
    "visibility_private": {"uz": "Private", "ru": "Приватный", "en": "Private"},
    "progression_immediate": {"uz": "To‘g‘ri javobdan keyin darhol", "ru": "Сразу после правильного ответа", "en": "Immediately after a correct answer"},
    "progression_scheduled": {"uz": "Jadval bo‘yicha", "ru": "По расписанию", "en": "At scheduled times"},
    "answer_auto": {"uz": "Avtomatik tekshiruv", "ru": "Автоматическая проверка", "en": "Automatic checking"},
    "answer_manual": {"uz": "Admin tekshiradi", "ru": "Проверяет администратор", "en": "Admin review"},
    "quest_card": {"uz": "{title}\nHolati: {status}\nBoshlanishi: {start}\nBosqichlar: {stages}\nTuri: {visibility}", "ru": "{title}\nСтатус: {status}\nНачало: {start}\nЭтапов: {stages}\nТип: {visibility}", "en": "{title}\nStatus: {status}\nStarts: {start}\nStages: {stages}\nVisibility: {visibility}"},
    "quest_details": {"uz": "{title}\n\n{description}\n\nHolati: {status}\nTuri: {visibility}\nBoshlanishi: {start}\nBosqichlar: {stages}\nKeyingi bosqich: {progression}\nUmumiy vaqt: {duration}\nSavollar chati: {chat}", "ru": "{title}\n\n{description}\n\nСтатус: {status}\nТип: {visibility}\nНачало: {start}\nЭтапов: {stages}\nПереход: {progression}\nОбщее время: {duration}\nЧат вопросов: {chat}", "en": "{title}\n\n{description}\n\nStatus: {status}\nVisibility: {visibility}\nStarts: {start}\nStages: {stages}\nProgression: {progression}\nOverall time: {duration}\nQuestion chat: {chat}"},
    "quest_not_found": {"uz": "Kvest topilmadi yoki unga kirish huquqingiz yo‘q.", "ru": "Квест не найден или у вас нет доступа.", "en": "Quest not found or you do not have access."},
    "join_success": {"uz": "Kvestga qo‘shildingiz. Savollar va javob natijalari botning shaxsiy chatiga keladi.", "ru": "Вы присоединились к квесту. Вопросы и результаты придут в личный чат с ботом.", "en": "You joined the quest. Questions and results will arrive in the bot’s private chat."},
    "already_joined": {"uz": "Siz bu kvestda allaqachon qatnashyapsiz.", "ru": "Вы уже участвуете в этом квесте.", "en": "You have already joined this quest."},
    "join_closed": {"uz": "Bu kvestga qo‘shilish yopilgan.", "ru": "В этот квест больше нельзя вступить.", "en": "Joining this quest is closed."},
    "private_link_invalid": {"uz": "Private kvest havolasi noto‘g‘ri yoki bekor qilingan.", "ru": "Ссылка на приватный квест неверна или отменена.", "en": "This private quest link is invalid or has been revoked."},
    "global_blocked": {"uz": "Botdan foydalanishingiz bloklangan.{reason}", "ru": "Доступ к боту заблокирован.{reason}", "en": "Your access to the bot is blocked.{reason}"},
    "blocked_notice": {"uz": "Siz ushbu kvestdan bloklandingiz.{reason}", "ru": "Вы заблокированы в этом квесте.{reason}", "en": "You have been blocked from this quest.{reason}"},
    "warning_blocked": {"uz": "⚠️ Siz “{title}” kvestidan bloklandingiz.{reason}", "ru": "⚠️ Вы заблокированы в квесте «{title}».{reason}", "en": "⚠️ You have been blocked from “{title}”.{reason}"},
    "reason_line": {"uz": " Sabab: {reason}", "ru": " Причина: {reason}", "en": " Reason: {reason}"},
    "btn_answer_privately": {"uz": "Javobni botga yuborish", "ru": "Ответить боту", "en": "Answer privately"},
    "ask_title": {"uz": "Kvest nomini yuboring:", "ru": "Отправьте название квеста:", "en": "Send the quest title:"},
    "ask_description": {"uz": "Kvest tavsifini yuboring:", "ru": "Отправьте описание квеста:", "en": "Send the quest description:"},
    "ask_visibility": {"uz": "Kvest turi:", "ru": "Тип квеста:", "en": "Choose quest visibility:"},
    "ask_stage_count": {"uz": "Bosqichlar sonini kiriting (1–30):", "ru": "Укажите количество этапов (1–30):", "en": "Enter the number of stages (1–30):"},
    "ask_progression": {"uz": "Keyingi bosqich qanday yuborilsin?", "ru": "Как отправлять следующий этап?", "en": "How should the next stage be delivered?"},
    "ask_start": {"uz": "Boshlanish vaqtini Toshkent vaqti bo‘yicha kiriting: YYYY-MM-DD HH:MM\nMasalan: 2026-10-03 18:30", "ru": "Введите время начала по Ташкенту: YYYY-MM-DD HH:MM\nНапример: 2026-10-03 18:30", "en": "Enter the start time in Tashkent local time: YYYY-MM-DD HH:MM\nExample: 2026-10-03 18:30"},
    "ask_duration": {"uz": "Umumiy vaqtni daqiqada kiriting. 0 — cheklanmagan:", "ru": "Общее время в минутах. 0 — без ограничения:", "en": "Overall time in minutes. Use 0 for no limit:"},
    "ask_chat": {"uz": "Savollar qayerda e’lon qilinsin? Guruh/kanalni tanlang yoki faqat botni tanlang.", "ru": "Где публиковать вопросы? Выберите группу/канал или только бота.", "en": "Where should questions be announced? Choose a group/channel or bot only."},
    "chat_private_only": {"uz": "Faqat bot", "ru": "Только бот", "en": "Bot only"},
    "ask_question": {"uz": "{number}-bosqich savolini yuboring:", "ru": "Отправьте вопрос для этапа {number}:", "en": "Send the question for stage {number}:"},
    "ask_answer_mode": {"uz": "Javobni kim tekshiradi?", "ru": "Кто проверяет ответ?", "en": "Who checks the answer?"},
    "ask_correct_answer": {"uz": "To‘g‘ri javobni kiriting. Harf registri hisobga olinadi:", "ru": "Введите правильный ответ. Регистр букв учитывается:", "en": "Enter the correct answer. Letter case matters:"},
    "ask_attempts": {"uz": "Ushbu bosqich uchun urinishlar soni (1–100):", "ru": "Число попыток для этого этапа (1–100):", "en": "Attempts allowed for this stage (1–100):"},
    "ask_stage_time": {"uz": "Bosqich vaqtini daqiqada kiriting. 0 — cheklanmagan:", "ru": "Лимит этапа в минутах. 0 — без ограничения:", "en": "Stage time limit in minutes. Use 0 for no limit:"},
    "ask_stage_start": {"uz": "{number}-bosqich vaqtini Toshkent vaqti bo‘yicha kiriting: YYYY-MM-DD HH:MM\nOldingi bosqichdan keyin bo‘lishi kerak.", "ru": "Введите время отправки этапа {number} по Ташкенту: YYYY-MM-DD HH:MM\nПозже предыдущего этапа.", "en": "Enter the delivery time for stage {number} in Tashkent time: YYYY-MM-DD HH:MM\nIt must be later than the previous stage."},
    "invalid_text": {"uz": "Matn bo‘sh bo‘lmasin va 1 000 belgidan oshmasin. Qayta yuboring.", "ru": "Текст не должен быть пустым и длиннее 1 000 символов. Попробуйте ещё раз.", "en": "Text must be non-empty and no longer than 1,000 characters. Try again."},
    "invalid_number": {"uz": "Qiymat noto‘g‘ri. Ko‘rsatilgan oraliqdagi butun sonni yuboring.", "ru": "Некорректное значение. Отправьте целое число из указанного диапазона.", "en": "Invalid value. Send a whole number in the stated range."},
    "invalid_datetime": {"uz": "Sana formati noto‘g‘ri yoki vaqt oldingi bosqichdan oldin. YYYY-MM-DD HH:MM kiriting.", "ru": "Неверный формат или время раньше предыдущего этапа. Используйте YYYY-MM-DD HH:MM.", "en": "Invalid format or a time before the previous stage. Use YYYY-MM-DD HH:MM."},
    "created": {"uz": "Kvest yaratildi: {title}\nBoshlanishi: {start}", "ru": "Квест создан: {title}\nНачало: {start}", "en": "Quest created: {title}\nStarts: {start}"},
    "cancelled": {"uz": "Amal bekor qilindi.", "ru": "Действие отменено.", "en": "Action cancelled."},
    "question_prefix": {"uz": "{title} — {number}-bosqich\n\n{question}\n\nUrinishlar: {attempts}{time}", "ru": "{title} — этап {number}\n\n{question}\n\nПопыток: {attempts}{time}", "en": "{title} — stage {number}\n\n{question}\n\nAttempts: {attempts}{time}"},
    "stage_time_hint": {"uz": "\nVaqt limiti: {minutes} daqiqa", "ru": "\nЛимит времени: {minutes} мин.", "en": "\nTime limit: {minutes} minutes"},
    "send_answer": {"uz": "Javobingizni shu chatga matn qilib yuboring.", "ru": "Отправьте ответ текстовым сообщением сюда.", "en": "Send your answer as a text message here."},
    "correct_next": {"uz": "✅ To‘g‘ri javob!", "ru": "✅ Верный ответ!", "en": "✅ Correct answer!"},
    "correct_wait": {"uz": "✅ To‘g‘ri! Keyingi bosqich belgilangan vaqtda yuboriladi.", "ru": "✅ Верно! Следующий этап придёт по расписанию.", "en": "✅ Correct! The next stage will arrive at its scheduled time."},
    "correct_done": {"uz": "🏁 To‘g‘ri! Kvestni yakunladingiz.", "ru": "🏁 Верно! Вы завершили квест.", "en": "🏁 Correct! You completed the quest."},
    "wrong_answer": {"uz": "❌ Javob noto‘g‘ri. Qolgan urinishlar: {remaining}.", "ru": "❌ Неверный ответ. Осталось попыток: {remaining}.", "en": "❌ Incorrect answer. Attempts remaining: {remaining}."},
    "attempts_exhausted": {"uz": "❌ Urinishlar tugadi. Ushbu kvestdagi ishtirokingiz yakunlandi.", "ru": "❌ Попытки закончились. Ваше участие в квесте завершено.", "en": "❌ No attempts remain. Your participation in this quest has ended."},
    "answer_pending": {"uz": "Javob admin tekshiruviga yuborildi.", "ru": "Ответ отправлен администратору на проверку.", "en": "Your answer was sent to the quest admin for review."},
    "no_active_question": {"uz": "Hozir javob berishingiz kerak bo‘lgan bosqich yo‘q.", "ru": "Сейчас нет открытого этапа для ответа.", "en": "There is no open stage for you to answer right now."},
    "choose_answer_quest": {"uz": "Bir nechta kvestda ochiq savolingiz bor. Javob bermoqchi bo‘lgan kvestni tanlang:", "ru": "У вас есть открытые вопросы в нескольких квестах. Выберите квест для ответа:", "en": "You have open questions in multiple quests. Choose which one to answer:"},
    "pending_admin_notice": {"uz": "Tekshirish kerak bo‘lgan javob: {user}, {title}, {stage}-bosqich.\n{answer}", "ru": "Ответ требует проверки: {user}, {title}, этап {stage}.\n{answer}", "en": "Answer needs review: {user}, {title}, stage {stage}.\n{answer}"},
    "stage_timeout": {"uz": "⏰ Bosqich vaqti tugadi. Ishtirokingiz yakunlandi.", "ru": "⏰ Время этапа истекло. Ваше участие завершено.", "en": "⏰ The stage timed out. Your participation has ended."},
    "quest_ended": {"uz": "Kvest yakunlandi.", "ru": "Квест завершён.", "en": "The quest has ended."},
    "admin_only": {"uz": "Bu amal faqat adminlar uchun.", "ru": "Действие доступно только администраторам.", "en": "This action is available to admins only."},
    "superadmin_only": {"uz": "Bu amal faqat superadmin uchun.", "ru": "Действие доступно только суперадминистратору.", "en": "This action is available to the superadmin only."},
    "admin_panel": {"uz": "Admin paneli", "ru": "Панель администратора", "en": "Admin panel"},
    "stats": {"uz": "Foydalanuvchilar: {users}\nAdminlar: {admins}\nKvestlar: {quests}\nDavom etayotgan: {active}\nYakunlangan: {completed}\nQatnashuvlar: {participants}", "ru": "Пользователи: {users}\nАдминистраторы: {admins}\nКвесты: {quests}\nИдут: {active}\nЗавершены: {completed}\nУчастия: {participants}", "en": "Users: {users}\nAdmins: {admins}\nQuests: {quests}\nOngoing: {active}\nCompleted: {completed}\nParticipations: {participants}"},
    "no_logs": {"uz": "Jurnal yozuvlari yo‘q.", "ru": "Записей журнала пока нет.", "en": "No audit entries yet."},
    "logs_title": {"uz": "So‘nggi harakatlar", "ru": "Последние действия", "en": "Recent actions"},
    "settings_page_size": {"uz": "Sahifadagi kvestlar soni: {size}", "ru": "Квестов на странице: {size}", "en": "Quests per page: {size}"},
    "choose_page_size": {"uz": "Sahifada ko‘rsatiladigan kvestlar soni:", "ru": "Количество квестов на странице:", "en": "Choose the number of quests per page:"},
    "admins_title": {"uz": "Adminlar ro‘yxati", "ru": "Список администраторов", "en": "Administrators"},
    "ask_admin_id": {"uz": "Yangi admin Telegram ID raqamini yuboring:", "ru": "Отправьте Telegram ID нового администратора:", "en": "Send the new admin’s Telegram numeric ID:"},
    "admin_added": {"uz": "Admin tayinlandi.", "ru": "Администратор назначен.", "en": "Admin appointed."},
    "admin_removed": {"uz": "Admin huquqi olib tashlandi.", "ru": "Права администратора сняты.", "en": "Admin access removed."},
    "invalid_admin_id": {"uz": "Telegram ID musbat son bo‘lishi kerak.", "ru": "Telegram ID должен быть положительным числом.", "en": "Telegram ID must be a positive number."},
    "confirm_finish": {"uz": "Kvestni yakunlaysizmi? Ishtirokchilar javob bera olmaydi.", "ru": "Завершить квест? Участники больше не смогут отвечать.", "en": "Finish this quest? Participants will no longer be able to answer."},
    "quest_finished": {"uz": "Kvest yakunlandi.", "ru": "Квест завершён.", "en": "Quest completed."},
    "quest_archived": {"uz": "Kvest arxivlandi.", "ru": "Квест архивирован.", "en": "Quest archived."},
    "quest_unarchived": {"uz": "Kvest arxivdan chiqarildi.", "ru": "Квест восстановлен из архива.", "en": "Quest unarchived."},
    "participants_title": {"uz": "Ishtirokchilar", "ru": "Участники", "en": "Participants"},
    "no_participants": {"uz": "Hozircha ishtirokchilar yo‘q.", "ru": "Пока нет участников.", "en": "There are no participants yet."},
    "ask_ban_reason": {"uz": "Bloklash sababini yuboring yoki tugmani bosing. Ishtirokchiga ogohlantirish yuboriladi.", "ru": "Отправьте причину блокировки или нажмите кнопку. Участник получит предупреждение.", "en": "Send a reason or press the button. The participant will be notified."},
    "blocked_success": {"uz": "Ishtirokchi bloklandi va ogohlantirildi.", "ru": "Участник заблокирован и уведомлён.", "en": "Participant blocked and notified."},
    "unblocked_success": {"uz": "Ishtirokchi blokdan chiqarildi.", "ru": "Участник разблокирован.", "en": "Participant unblocked."},
    "leaderboard_title": {"uz": "🏆 Reyting: {title}", "ru": "🏆 Рейтинг: {title}", "en": "🏆 Leaderboard: {title}"},
    "leaderboard_empty": {"uz": "Reyting uchun ma’lumot yo‘q.", "ru": "Данных для рейтинга нет.", "en": "No leaderboard data yet."},
    "leaderboard_row": {"uz": "{rank}. {name} — {solved} bosqich, {status}", "ru": "{rank}. {name} — этапов: {solved}, {status}", "en": "{rank}. {name} — {solved} stages, {status}"},
    "role_admin": {"uz": "Admin", "ru": "Админ", "en": "Admin"},
    "role_superadmin": {"uz": "Superadmin", "ru": "Суперадмин", "en": "Superadmin"},
    "participant_joined": {"uz": "qo‘shilgan", "ru": "присоединился", "en": "joined"},
    "participant_active": {"uz": "qatnashmoqda", "ru": "участвует", "en": "active"},
    "participant_completed": {"uz": "yakunlagan", "ru": "завершил", "en": "completed"},
    "participant_failed": {"uz": "urinish tugagan", "ru": "попытки исчерпаны", "en": "out of attempts"},
    "participant_blocked": {"uz": "bloklangan", "ru": "заблокирован", "en": "blocked"},
    "support_choose": {"uz": "Kimga murojaat qilmoqchisiz?", "ru": "Кому вы хотите написать?", "en": "Who would you like to contact?"},
    "support_no_quests": {"uz": "Kvest adminiga yozish uchun qatnashgan kvestingiz yo‘q.", "ru": "Нет квестов, в которых вы участвовали.", "en": "You have no participating quests to contact an admin about."},
    "support_ask": {"uz": "Xabaringizni yuboring. Bekor qilish uchun /cancel.", "ru": "Отправьте сообщение. Для отмены — /cancel.", "en": "Send your message. Use /cancel to stop."},
    "support_created": {"uz": "Murojaatingiz yuborildi. Javob bot orqali keladi.", "ru": "Обращение отправлено. Ответ придёт через бота.", "en": "Your support message was sent. Replies arrive through the bot."},
    "support_notification": {"uz": "Yangi murojaat #{ticket} (foydalanuvchi {user}):\n{message}", "ru": "Новое обращение #{ticket} (пользователь {user}):\n{message}", "en": "New support ticket #{ticket} (user {user}):\n{message}"},
    "support_reply_prompt": {"uz": "#{ticket} murojaatiga javob yuboring:", "ru": "Отправьте ответ на обращение #{ticket}:", "en": "Send your reply to ticket #{ticket}:"},
    "support_reply_to_user": {"uz": "Yordam javobi (#{ticket}):\n{message}", "ru": "Ответ поддержки (#{ticket}):\n{message}", "en": "Support reply (#{ticket}):\n{message}"},
    "support_reply_to_admin": {"uz": "#{ticket} murojaatiga yangi xabar:\n{message}", "ru": "Новое сообщение в обращении #{ticket}:\n{message}", "en": "New message in ticket #{ticket}:\n{message}"},
    "no_tickets": {"uz": "Murojaatlaringiz yo‘q.", "ru": "У вас нет обращений.", "en": "You have no support tickets."},
    "ticket_history": {"uz": "Murojaat #{ticket} ({status}):\n{messages}", "ru": "Обращение #{ticket} ({status}):\n{messages}", "en": "Ticket #{ticket} ({status}):\n{messages}"},
    "ticket_open": {"uz": "ochiq", "ru": "открыто", "en": "open"},
    "ticket_closed": {"uz": "yopiq", "ru": "закрыто", "en": "closed"},
    "admin_review_title": {"uz": "Tekshiruvdagi javoblar", "ru": "Ответы на проверке", "en": "Answers awaiting review"},
    "no_pending": {"uz": "Tekshiriladigan javob yo‘q.", "ru": "Нет ответов на проверке.", "en": "No answers are waiting for review."},
    "review_item": {"uz": "{name}, {stage}-bosqich:\n{answer}", "ru": "{name}, этап {stage}:\n{answer}", "en": "{name}, stage {stage}:\n{answer}"},
    "review_approved": {"uz": "Javob to‘g‘ri deb tasdiqlandi.", "ru": "Ответ принят как верный.", "en": "Answer approved as correct."},
    "review_rejected": {"uz": "Javob noto‘g‘ri deb belgilandi.", "ru": "Ответ отмечен как неверный.", "en": "Answer rejected as incorrect."},
    "review_to_user": {"uz": "Kvest admini javobingizni {result} deb belgiladi.", "ru": "Администратор отметил ваш ответ как {result}.", "en": "The quest admin marked your answer {result}."},
    "correct_result": {"uz": "to‘g‘ri", "ru": "верным", "en": "correct"},
    "wrong_result": {"uz": "noto‘g‘ri", "ru": "неверным", "en": "incorrect"},
    "ask_chat_id": {"uz": "Guruh/kanal chat ID raqamini yuboring. Bot shu chatda admin bo‘lishi kerak; ID olish uchun guruhda /chatid buyrug‘idan foydalaning.", "ru": "Отправьте chat ID группы/канала. Бот должен быть администратором; чтобы узнать ID, используйте /chatid в чате.", "en": "Send the group/channel chat ID. The bot must be an admin there; use /chatid in that chat to find the ID."},
    "chat_added": {"uz": "Chat ro‘yxatga qo‘shildi: {title}", "ru": "Чат добавлен: {title}", "en": "Chat registered: {title}"},
    "chat_not_found": {"uz": "Chat topilmadi yoki botda kerakli admin huquqlari yo‘q.", "ru": "Чат не найден или у бота нет необходимых прав администратора.", "en": "Chat not found or the bot lacks required administrator rights."},
    "chat_permission_missing": {"uz": "Botga kanalda xabar yuborish yoki a’zolarni cheklash uchun kerakli admin huquqini bering.", "ru": "Дайте боту право публиковать сообщения в канале или ограничивать участников.", "en": "Grant the bot permission to post in the channel or restrict chat members."},
    "chats_empty": {"uz": "Ro‘yxatga olingan guruh/kanal yo‘q.", "ru": "Нет зарегистрированных групп/каналов.", "en": "No groups/channels are registered."},
    "chat_info": {"uz": "{title}\nID: {chat_id}\nBoshlanishda a’zolarni chiqarish: {cleanup}", "ru": "{title}\nID: {chat_id}\nУдалять участников при старте: {cleanup}", "en": "{title}\nID: {chat_id}\nRemove known members at start: {cleanup}"},
    "cleanup_on": {"uz": "yoqilgan", "ru": "включено", "en": "enabled"},
    "cleanup_off": {"uz": "o‘chirilgan", "ru": "выключено", "en": "disabled"},
    "whitelist_title": {"uz": "Chiqarilmaydigan user ID’lar", "ru": "Исключённые из удаления user ID", "en": "User IDs excluded from removal"},
    "ask_whitelist_id": {"uz": "Chiqarilmaydigan foydalanuvchining Telegram ID raqamini yuboring:", "ru": "Отправьте Telegram ID пользователя, которого нельзя удалять:", "en": "Send the Telegram ID of a user to exclude from removal:"},
    "whitelist_added": {"uz": "Istisno ro‘yxatiga qo‘shildi.", "ru": "Добавлено в список исключений.", "en": "Added to the exclusion list."},
    "whitelist_removed": {"uz": "Istisno ro‘yxatidan olindi.", "ru": "Удалено из списка исключений.", "en": "Removed from the exclusion list."},
    "no_whitelist": {"uz": "Istisnolar yo‘q.", "ru": "Исключений нет.", "en": "No exclusions."},
    "invite_link_ready": {"uz": "Chatga kirish uchun bir kishilik, muddatsiz havola:\n{link}\nHavolani olgan odam bilan shaxsiy ulashing.", "ru": "Одноразовая бессрочная ссылка в чат:\n{link}\nПередавайте её адресно.", "en": "One-person, non-expiring chat invite:\n{link}\nShare it privately with the intended person."},
    "invite_unavailable": {"uz": "Chatga havola yaratib bo‘lmadi. Botda invite link yaratish huquqi bo‘lishi kerak.", "ru": "Не удалось создать ссылку. Боту нужно право приглашать участников.", "en": "Could not create the invite. The bot needs permission to invite members."},
    "invite_at_start": {"uz": "Chatga kirish uchun havola kvest boshlanganda yuboriladi.", "ru": "Ссылка для входа в чат придёт после начала квеста.", "en": "The chat invite link will be sent when the quest starts."},
    "error_generic": {"uz": "Xatolik yuz berdi. Qayta urinib ko‘ring.", "ru": "Произошла ошибка. Попробуйте ещё раз.", "en": "Something went wrong. Please try again."},
}


def tr(language: str | None, key: str, **values: object) -> str:
    """Translate and format a message, falling back to Uzbek for unknown languages."""
    lang = language if language in LANGUAGES else "uz"
    text = TEXTS.get(key, {}).get(lang) or TEXTS.get(key, {}).get("en") or key
    try:
        return text.format(**values)
    except KeyError:
        return text
