"""Karakalpak (Qaraqalpaqsha) interface texts.

The dictionary covers every key of ``quest_bot.localization.TEXTS`` so the
language can be selected like Uzbek, Russian, and English.
"""

from __future__ import annotations

KARAKALPAK_TEXTS: dict[str, str] = {
    "welcome": "Quest Botqa xosh keldińiz! Kvestlerdi tabıń, qatnasıń yamasa ózińiz jaratıń.",
    "menu": "Bas menyu",
    "btn_quests": "🔎 Kvestlerdi kóriw",
    "btn_my_quests": "🛠️ Men basqaratuǵın kvestler",
    "btn_my_participations": "🙋 Qatnasıp atırǵan kvestlerim",
    "btn_admin": "🛠️ Administrator paneli",
    "btn_ratings": "🏆 Reytingler",
    "btn_public_quest_ratings": "🏆 Ashıq kvestler reytingi",
    "btn_managed_ratings": "🏆 Basqarılatuǵın kvestler reytingi",
    "period_week": "📅 Usı hápte",
    "period_month": "📆 Usı ay",
    "period_year": "🗓 Usı jıl",
    "btn_guide": "📖 Qollanba",
    "btn_support": "💬 Járdem / múrájat",
    "btn_language": "🌐 Tildi tańlaw",
    "btn_back": "⬅️ Artqa",
    "btn_home": "🏠 Bas menyu",
    "btn_admin_home": "🛠 Administrator paneli",
    "btn_cancel": "❌ Biykar etiw",
    "btn_confirm": "✅ Tastıyıqlaw",
    "btn_join": "✅ Qatnasıw",
    "btn_confirm_join": "✅ Qatnasıwdı tastıyıqlaw",
    "btn_skip_photo": "⏭️ Súwretsiz dawam etiw",
    "btn_edit_details": "🛠 Kvest maǵlıwmatların redaktorlaw",
    "btn_edit_title": "✏️ Atın ózgertiw",
    "btn_edit_description": "📝 Táriypin ózgertiw",
    "btn_edit_cover": "🖼 Muqaba súwretin ózgertiw",
    "btn_replace_cover": "📷 Súwret qosıw yamasa almastırıw",
    "btn_remove_cover": "🗑️ Muqaba súwretin alıp taslaw",
    "btn_confirm_remove_cover": "🗑️ Awa, alıp taslaw",
    "btn_private_link": "🔗 Kvest shaqırıw siltemesin alıw",
    "btn_open": "👁️ Kóriw",
    "btn_create": "➕ Kvest jaratıw",
    "btn_manage": "⚙️ Basqarıw",
    "btn_edit_questions": "✏️ Sorawlardı redaktorlaw",
    "btn_edit_question": "✏️ Sorawdı ózgertiw",
    "btn_add_stage": "➕ Basqısh qosıw",
    "btn_remove_stage": "🗑️ Basqıshtı alıp taslaw",
    "btn_confirm_remove_stage": "🗑️ Awa, alıp taslaw",
    "btn_edit_answer": "✏️ Durıs juwaptı ózgertiw",
    "btn_rank": "🏆 Reyting",
    "btn_participants": "👥 Qatnasıwshılar",
    "btn_pending": "🔎 Tekseriwdegi juwaplar",
    "btn_invite": "🔗 Toparǵa bir adamlıq silteme",
    "btn_finish": "🏁 Kvestti juwmaqlaw",
    "btn_pause": "⏸️ Kvestti waqıtsha toqtatıw",
    "btn_resume": "▶️ Kvestti dawam ettiriw",
    "btn_archive": "📦 Arxivlaw",
    "btn_unarchive": "📤 Arxivtan shıǵarıw",
    "btn_ban": "🚫 Bloklaw",
    "btn_unban": "✅ Bloktan shıǵarıw",
    "btn_approve": "✅ Durıs",
    "btn_reject": "❌ Nádurıs",
    "btn_skip": "⏭️ Sebepsiz dawam etiw",
    "btn_add": "➕ Qosıw",
    "btn_remove": "🗑️ Alıp taslaw",
    "btn_toggle_cleanup": "🧹 Shıǵarıw sazlamasın ózgertiw",
    "btn_whitelist": "🛡️ Ayırıqshalıqlar dizimi",
    "btn_admins": "👥 Administratorlardı basqarıw",
    "btn_stats": "📊 Statistika",
    "btn_logs": "📜 Háreketler jurnalı",
    "btn_settings": "⚙️ Sazlamalar",
    "btn_export": "📤 Maǵlıwmatlardı eksportlaw",
    "btn_chats": "📣 Toparlar/kanallar",
    "btn_support_super": "👑 Bas administratorǵa jazıw",
    "btn_support_quest": "👤 Kvest administratorına jazıw",
    "btn_my_tickets": "🎫 Mening múrájatlarım",
    "btn_reply": "↩️ Juwan jazıw",
    "btn_reply_ticket": "↩️ Juwan beriw",
    "open_private_chat": "🔒 Dawam etiw ushın bot penen jeke chattı ashıń.",
    "chat_id_result": "Chat ID: {chat_id}\nAtı: {title}",
    "welcome_hint": "Tildi almastırıw ushın /language buyrıǵınan paydalanıń.",
    "guide": (
        "Qollanba:\n"
        "1. «Kvestlerdi kóriw» arqalı ashıq kvestlerdi tabıń. Jasırın kvest bottıń shaqırıw siltemesi arqalı ashıladı.\n"
        "2. Kvest baslanǵanda xabar keledi; soraw «Baslaw»/«Dawam etiw» túymesi basılǵanda bottıń jeke chatına jiberiledi. Kvestke biriktirilgen topar/kanal bar bolsa, járiyalar sonnda shıǵadı; juwaplar botqa jeke chatta jiberiledi.\n"
        "3. Juwap saqlanǵan juwap penen tap-takır salıstırıladı; bas/aqırındaǵı bos orınlar alıp taslanadı, úlken-kishi hárip parqı saqlanadı. Administrator tekseretuǵın basqıshlarda nátiyjeni administrator belgileydi.\n"
        "4. Reytingdi kvest betinen yamasa «Reytingler» bóliminen baqlap barıń.\n"
        "5. Járdem arqalı bas administratorǵa yamasa tiyisli kvest administratorına jazıń.\n\n"
        "Administrator óz kvestin jaratadı hám basqaradı; basqarılatuǵın kvestler dizimi «Administrator paneli» ishinde. Bas administrator administratorlardı, barlıq kvestlerdi, arxivti, statistikanı, háreketler jurnalın hám sazlamalardı basqaradı. Botta reklama joq."
    ),
    "language_choose": "🌐 Interfeys tilin tańlań:",
    "language_saved": "✅ Til Qaraqalpaqsha etip saqlandı.",
    "language_button": "Qaraqalpaqsha",
    "quests_title": "🔎 Ashıq kvestler",
    "my_quests_title": "🛠️ Basqarılatuǵın kvestler",
    "my_participating_quests_title": "🙋 Siz qatnasıp atırǵan kvestler",
    "empty_quests": "📭 Bul bólimde kvest tabılmadı.",
    "filter_all": "📋 Barlıǵı",
    "filter_scheduled": "🕒 Kútilmekte",
    "filter_active": "🟢 Dawam etpekte",
    "filter_completed": "✅ Juwmaqlanǵan",
    "filter_archived": "🗄️ Arxivlengen",
    "status_scheduled": "🕒 Kútilmekte",
    "status_active": "🟢 Dawam etpekte",
    "status_completed": "✅ Juwmaqlanǵan",
    "status_archived": "🗄️ Arxivlengen",
    "status_paused": "⏸️ Waqıtsha toqtatılǵan",
    "visibility_public": "🌐 Ashıq",
    "visibility_private": "🔒 Jasırın",
    "progression_immediate": "⚡ Durıs juwaptan keyin derhal",
    "progression_scheduled": "📅 Keste boyınsha",
    "answer_auto": "🤖 Avtomatik tekseriw",
    "answer_manual": "👤 Administrator tekseredi",
    "quest_card": "{title}\nHalatı: {status}\nBaslanıwı: {start}\nBasqıshlar: {stages}\nTúri: {visibility}",
    "quest_details": (
        "{title}\n\n{description}\n\nHalatı: {status}\nTúri: {visibility}\n"
        "Baslanıwı: {start}\nBasqıshlar: {stages}\nKeyingi basqısh: {progression}\n"
        "Ulıwma waqıt: {duration}\nSorawlar toparı: {chat}\nQatnasıwshılar: {participants}"
    ),
    "quest_label_description": "Táriyp",
    "quest_label_status": "Halatı",
    "quest_label_visibility": "Túri",
    "quest_label_start": "Baslanıw waqtı",
    "quest_label_stages": "Basqıshlar sanı",
    "quest_label_participants": "Qatnasıwshılar sanı",
    "quest_label_progression": "Keyingi basqısh",
    "quest_label_duration": "Ulıwma waqıt",
    "quest_label_chat": "Sorawlar toparı",
    "quest_not_found": "⚠️ Kvest tabılmadı yamasa oǵan kiriw huqıqıńız joq.",
    "join_success": "✅ Siz kvestke qosıldıńız. Kvest baslanǵanda sizge xabar jiberiledi; soraw «Baslaw» túmesi basılǵanda jiberiledi.",
    "already_joined": "Siz bul kvestte álleqashan qatnasıp atırsız.",
    "join_closed": "Bul kvestke qosılıw jayılǵan.",
    "join_confirmation_prompt": "Kvestke qosılıwdı tastıyıqlaysız ba?",
    "join_cancelled": "Kvestke qosılıw biykar etildi.",
    "quest_paused_notice": "Kvest waqıtsha toqtatılǵan. Dawam ettirilgennen keyin qayta urınıp kóriń.",
    "pause_success": "Kvest waqıtsha toqtatıldı. Keste hám múddetler usı waqıt ishinde esaplanbaydı.",
    "resume_success": "Kvest dawam ettirildi. Keste hám múddetler toqtatılǵan waqıtqa jıljıtıldı.",
    "private_link_invalid": "Jasırın kvest siltemesi nadurıs yamasa biykar etilgen.",
    "global_blocked": "Botdan paydalanıwıńız bloklanǵan.{reason}",
    "blocked_notice": "Siz bul kvestten bloklandıńız.{reason}",
    "warning_blocked": "⚠️ Siz «{title}» kvestinen bloklandıńız.{reason}",
    "reason_line": " Sebep: {reason}",
    "btn_answer_privately": "✉️ Juwaptı botqa jiberiw",
    "ask_title": "✏️ Kvest atın jiberiń:",
    "ask_description": "📝 Kvest táriypin jiberiń:",
    "ask_cover_photo": "📷 Kvest muqabası ushın súwret jiberiń yamasa súwretsiz dawam etiń:",
    "invalid_cover_photo": "Muqaba ushın súwret jiberiń yamasa «Súwretsiz dawam etiw» túymesin basıń.",
    "ask_visibility": "🌐 Kvest túri:",
    "ask_stage_count": "Basqıshlar sanın kiritiń (1–30):",
    "ask_progression": "⚙️ Keyingi basqısh qanday jiberilsin?",
    "ask_start": "Baslanıw waqtın Tashkent waqtı boyınsha kiritiń: YYYY-MM-DD HH:MM\nMısalı: 2026-10-03 18:30",
    "ask_duration": "Ulıwma waqıttı minutta kiritiń. 0 — sheklengen emes:",
    "ask_chat": "Sorawlar qayerde járiyalansın? Topar/kanaldı tańlań yamasa tek bottı tańlań.",
    "chat_private_only": "Tek bot",
    "ask_question": "❓ {number}-basqısh ushın tekst, súwret yamasa video jiberiń (eskertpe ixtıyarlı):",
    "invalid_question": "Soraw ushın tekst, súwret yamasa video jiberiń. Tekst 4096, eskertpe bolsa 1024 belgiden aspasın.",
    "invalid_correct_answer": "Durıs juwap bos bolmasın hám 300 belgiden aspasın. Qayta jiberiń:",
    "question_archive_failed": "Sorawdı arxiv kanalına kóshirip bolmadı. Bot kanal administratorı ekenin hám xabar jaylastırıw huqıqı barın tekseriń.",
    "ask_answer_mode": "🤖 Juwaptı kim tekseredi?",
    "ask_correct_answer": "✅ Durıs juwaptı kiritiń. Hárip registri esapqa alınadı:",
    "ask_attempts": "🔢 Usı basqısh ushın urınıslar sanı (1–100):",
    "ask_stage_time": "⏳ Basqısh waqtın minutta kiritiń. 0 — sheklengen emes:",
    "ask_stage_start": "📅 {number}-basqısh waqtın Tashkent waqtı boyınsha kiritiń: YYYY-MM-DD HH:MM\nAldıńǵı basqıshtan keyin hám ulıwma múddet ishinde bolsın (awısqan kvestte — keleshektegi waqıt).",
    "stage_schedule_invalid": "⚠️ Waqıt aldıńǵı basqıshtan keyin hám ulıwma múddet ishinde bolıwı kerek (awısqan kvestte — keleshekte).",
    "invalid_text": "⚠️ Tekst bos bolmasın hám 1 000 belgiden aspasın. Qayta jiberiń.",
    "invalid_number": "⚠️ Mánis nadurıs. Kórsetilgen aralıqtaǵı pútin sandı jiberiń.",
    "invalid_datetime": "⚠️ Sana formatı nadurıs yamasa waqıt aldıńǵı basqıshtan burın. YYYY-MM-DD HH:MM kiritiń.",
    "created": "✅ Kvest jaratıldı: {title}\nBaslanıwı: {start}",
    "cancelled": "↩️ Ámel biykar etildi.",
    "question_prefix": "{title} — {number}-basqısh\n\n{question}\n\nUrınıslar: {attempts}{time}",
    "stage_meta": "{title} — {number}-basqısh\nUrınıslar: {attempts}{time}",
    "stage_label": "🧩 {number}-basqısh",
    "stage_attempts": "Urınıslar",
    "quest_label_title": "Kvest atı",
    "edit_quest_details_title": "Kvest maǵlıwmatların redaktorlaw",
    "edit_quest_details_hint": "Attı, táriypin hám muqaba súwretin ózgertiń. Bul maǵlıwmatlardı kvest juwmaqlanǵannan keyin de, arxivlanbaǵansha redaktorlaw múmkin.",
    "edit_quest_cover_title": "Kvest muqabası",
    "edit_quest_cover_missing": "📭 Ázirge muqaba súwreti qosılmaǵan.",
    "edit_quest_cover_has_photo": "✅ Muqaba súwreti bar. Tómende aǵımdaǵı nusqası kórsetilgen.",
    "ask_quest_title": "Kvesttiń jańa atın jiberiń (1–100 belgi):",
    "ask_quest_description": "Kvesttiń jańa táriypin jiberiń (1–1 000 belgi):",
    "ask_quest_cover": "Jańa muqaba ushın súwret jiberiń. Aǵımdaǵı súwret jańa súwret tabıslı saqlanǵannan keyin almastırıladı.",
    "invalid_quest_title": "At 1–100 belgiden ibarat bolıwı kerek. Qayta jiberiń:",
    "invalid_quest_description": "Táriyp 1–1 000 belgiden ibarat bolıwı kerek. Qayta jiberiń:",
    "invalid_quest_cover": "Muqaba ushın súwret jiberiń yamasa biykar etiw túymesin basıń.",
    "confirm_remove_cover": "Usı kvesttiń muqaba súwretin alıp taslaysız ba? Arxivtaǵı nusqası da óshiriledi.",
    "quest_title_updated": "Kvest atı jańalandı.",
    "quest_description_updated": "Kvest táriypi jańalandı.",
    "quest_cover_updated": "Kvest muqabası jańalandı.",
    "quest_cover_removed": "Kvest muqabası alıp taslandı.",
    "quest_metadata_archived": "⚠️ Arxivlengen kvest maǵlıwmatların redaktorlap bolmaydı.",
    "edit_questions_title": "📚 Redaktorlaw múmkin bolǵan basqıshtı tańlań. Jiberilgen sorawlar ózgermeydi.",
    "no_editable_stages": "📭 Ázirge redaktorlaw múmkin bolǵan soraw joq.",
    "edit_stage_title": "✏️ {number}-basqıshtı redaktorlaw:",
    "confirm_remove_stage": "{number}-basqıshtı alıp taslaysız ba? Keyingi basqıshlar nomeri avtomatik jańalanadı.",
    "stage_added": "✅ {number}-basqısh qosıldı. Jámi basqıshlar: {count}.",
    "stage_removed": "✅ Basqısh alıp taslandı. Jámi basqıshlar: {count}.",
    "stage_limit_reached": "⚠️ Kvestte eń kóp 30 basqısh bolıwı múmkin.",
    "ask_replacement_question": "✏️ Jańa tekst, súwret yamasa video jiberiń. Media ushın eskertpe ixtıyarlı.",
    "ask_replacement_answer": "✅ Jańa durıs juwaptı jiberiń:",
    "stage_question_updated": "✅ Soraw jańalandı.",
    "stage_answer_updated": "✅ Durıs juwap jańalandı.",
    "stage_not_editable": "⚠️ Bul basqısh álleqashan jiberilgen yamasa redaktorlaw ushın jayılǵan.",    "edit_cancelled": "↩️ Redaktorlaw biykar etildi.",
    "stage_time_hint": "\nWaqıt shegi: {minutes} minut",
    "send_answer": "Juwapıńızdı usı chatqa tekst etip jiberiń.",
    "correct_next": "✅ Durıs juwap! Keyingi basqıshqa ótiw ushın «{button}» túymesin basıń.",
    "correct_wait": "✅ Durıs! Keyingi basqısh belgilengen waqıtta jiberiledi.",
    "correct_done": "🏁 Durıs! Kvestti juwmaqladıńız.",
    "wrong_answer": "❌ Juwap nádurıs. Qalǵan urınıslar: {remaining}.",
    "attempts_exhausted": "❌ Urınıslar tawsıldı. Usı kvesttegi qatnasıwıńız juwmaqlandı.",
    "answer_pending": "Juwap administrator tekseriwine jiberildi.",
    "no_active_question": "Házir juwap beriwińiz kerek bolǵan basqısh joq.",
    "choose_answer_quest": "Bir neshe kvestte ashıq sorawıńız bar. Juwap bermekshi bolǵan kvestti tańlań:",
    "pending_admin_notice": "Tekseriw kerek bolǵan juwap: {user}, {title}, {stage}-basqısh.\n{answer}",
    "stage_timeout": "⏰ Basqısh waqtı tawsıldı. Qatnasıwıńız juwmaqlandı.",
    "quest_ended": "Kvest juwmaqlandı.",
    "admin_only": "🔒 Bul ámel tek administratorlar ushın.",
    "superadmin_only": "🔒 Bul ámel tek bas administrator ushın.",
    "admin_panel": "🛠️ Administrator paneli",
    "stats": (
        "👥 Paydalanıwshılar jámi: {users}\n"
        "🆕 Aqırǵı 30 kúnde jańa: {new_users_30d}\n"
        "🟢 Belsendi (7 kún): {active_users_7d}\n"
        "📅 Belsendi (30 kún): {active_users_30d}\n"
        "🌐 Til boyınsha: ózbeksha {language_uz}, jańa ózbeksha {language_uzn}, qaraqalpaqsha {language_kaa}, russha {language_ru}, inglishshe {language_en}\n\n"
        "🛡 Administratorlar: {admins}\n"
        "🧭 Kvestler jámi: {quests}\n"
        "🟢 Belsendi kvestler: {active}\n"
        "⏸️ Waqıtsha toqtatılǵan kvestler: {paused}\n"
        "✅ Juwmaqlanǵan kvestler: {completed}\n"
        "👥 Qatnasıwlar: {participants} ({participating_users} paydalanıwshı)\n"
        "🏁 Juwmaqlanǵan qatnasıwlar: {completed_participations} ({participation_completion_percent}%)"
    ),
    "no_logs": "Jurnal jazıwları joq.",
    "logs_title": "📜 Aqırǵı háreketler",
    "settings_page_size": "⚙️ Betindegi kvestler sanı: {size}",
    "choose_page_size": "🔢 Betinde kórsetiletuǵın kvestler sanı:",
    "admins_title": "👥 Administratorlar dizimi",
    "ask_admin_id": "Jańa administratordıń Telegram ID nomerin jiberiń:",
    "admin_added": "Administrator tayınlandı.",
    "admin_removed": "Administrator huqıqı alıp taslandı.",
    "invalid_admin_id": "Telegram ID oń san bolıwı kerek.",
    "confirm_finish": "Kvestti juwmaqlaysız ba? Qatnasıwshılar juwap bere almaydı.",
    "quest_finished": "Kvest juwmaqlandı.",
    "quest_archived": "Kvest arxivlandı.",
    "quest_unarchived": "Kvest arxivtan shıǵarıldı.",
    "btn_message_participant": "✉️ Xabar jiberiw",
    "participants_title": "Qatnasıwshılar",
    "ask_participant_message": "✉️ {user}ǵa «{title}» kvesti boyınsha xabar tekstin jiberiń (1–2 000 belgi). Biykar etiw ushın /cancel buyrıǵın jiberiń.",
    "participant_message_heading": "📩 Bas administratordan xabar · {title}",
    "participant_message_sent": "✅ Xabar {user}ǵa jiberildi.",
    "invalid_participant_message": "⚠️ Xabar bos bolmaslıǵı hám 2 000 belgiden aspaslıǵı kerek.",
    "participant_message_delivery_failed": "⚠️ Xabar jetkerilmadi. Qatnasıwshı bottı bloklaǵan bolıwı múmkin.",
    "participant_message_unavailable": "⚠️ Kvest qatnasıwshısı tabılmadı.",
    "participant_message_finish_current_flow": "Aldın dawam etip atırǵan ámeldi juwmaqlań yamasa /cancel buyrıǵın jiberiń.",
    "no_participants": "Ázirge qatnasıwshılar joq.",
    "ask_ban_reason": "Bloklaw sebebin jiberiń yamasa túymeni basıń. Qatnasıwshıǵa eskertiw jiberiledi.",
    "blocked_success": "Qatnasıwshı bloklandı hám eskertildi.",
    "unblocked_success": "Qatnasıwshı bloktan shıǵarıldı.",
    "leaderboard_title": "🏆 Reyting: {title}",
    "leaderboard_empty": "Reyting ushın maǵlıwmat joq.",
    "leaderboard_row": "{rank}. {name} — {solved} basqısh, {status}{completion}",
    "leaderboard_completion": " · juwmaqlandı: {time}",
    "ratings_overview_title": "Ashıq kvestlerdiń ulıwma reytingi",
    "aggregate_leaderboard_title": "🏆 {period} reytingi",
    "aggregate_leaderboard_row": "{rank}. {name} — {points} ball, {completed} kvest juwmaqlanǵan",
    "aggregate_leaderboard_empty": "Bul dáwirde nátiyjeler joq.",
    "role_admin": "Administrator",
    "role_superadmin": "Bas administrator",
    "participant_joined": "🟡 qosılǵan",
    "participant_active": "🟢 qatnasıp atır",
    "participant_completed": "✅ juwmaqlaǵan",
    "participant_failed": "❌ urınısı tawsılǵan",
    "participant_blocked": "🚫 bloklanǵan",
    "support_choose": "Kimge múrájat etpekshisiz?",
    "support_no_quests": "Kvest adminine jazıw ushın qatnasqan kvestińiz joq.",
    "support_ask": "Xabarıńızdı jiberiń. Biykar etiw ushın /cancel.",
    "support_created": "Múrájatıńız jiberildi. Juwap bot arqalı keledi.",
    "support_notification": "Jańa múrájat #{ticket} (paydalanıwshı {user}):\n{message}",
    "support_reply_prompt": "#{ticket} múrájatına juwap jiberiń:",
    "support_you": "Siz",
    "support_admin_reply_sent": "Juwap jiberildi.",
    "support_reply_to_user": "#{ticket} múrájatı · {source}:\n{message}",
    "support_source_quest_admin": "«{quest}» kvesti administratorı",
    "support_source_superadmin": "Bas administrator",    "support_thread_notification": "#{ticket} múrájatı · {source}\nPaydalanıwshı: {user}\n{message}",
    "support_history_line": "{sender}: {message}",
    "support_reply_to_admin": "#{ticket} múrájatına jańa xabar:\n{message}",
    "no_tickets": "Múrájatlarıńız joq.",
    "ticket_history": "Múrájat #{ticket} ({status}):\n{messages}",
    "ticket_open": "📬 ashıq",
    "ticket_closed": "✅ jayılǵan",
    "admin_review_title": "Tekseriwdegi juwaplar",
    "no_pending": "Tekseriletuǵın juwap joq.",
    "review_item": "{name}, {stage}-basqısh:\n{answer}",
    "review_approved": "Juwap durıs dep tastıyıqlandı.",
    "review_rejected": "Juwap nádurıs dep belgilendi.",
    "review_to_user": "Kvest administratorı juwapıńızdı {result} dep belgiledi.",
    "correct_result": "durıs",
    "wrong_result": "nádurıs",
    "ask_chat_id": "Topar/kanal chat ID nomerin jiberiń. Bot usı chatta administrator bolıwı kerek; ID alıw ushın toparda /chatid buyrıǵınan paydalanıń.",
    "chat_added": "Topar yamasa kanal dizimge qosıldı: {title}",
    "chat_not_found": "Topar yamasa kanal tabılmadı yamasa botta kerekli administrator huqıqları joq.",
    "chat_permission_missing": "Botqa kanalda xabar jiberiw yamasa aǵzalardı sheklew ushın kerekli administrator huqıqın beriń.",
    "chats_empty": "Dizimge alınǵan topar/kanal joq.",
    "chat_info": "{title}\nID: {chat_id}\nBaslanıwda aǵzalardı shıǵarıw: {cleanup}",
    "cleanup_on": "qosılǵan",
    "cleanup_off": "óshirilgen",
    "whitelist_title": "Shıǵarıwdan ayırıqshalanǵan paydalanıwshılar ID nomerleri",
    "ask_whitelist_id": "Shıǵarılmaytuǵın paydalanıwshınıń Telegram ID nomerin jiberiń:",
    "whitelist_added": "Ayırıqshalıqlar dizimine qosıldı.",
    "whitelist_removed": "Ayırıqshalıqlar diziminen alındı.",
    "no_whitelist": "Ayırıqshalıqlar joq.",
    "invite_link_ready": "Toparǵa kiriw ushın bir adamlıq, múddetsiz silteme:\n{link}\nSiltemeni alǵan adam menen jeke bólisiń.",
    "invite_unavailable": "Toparǵa silteme jaratıp bolmadı. Botta shaqırıw siltemesi jaratıw huqıqı bolıwı kerek.",
    "invite_at_start": "Toparǵa kiriw ushın silteme kvest baslanǵanda jiberiledi.",
    "service_started": "✅ Quest Bot iske túsirildi.",
    "service_stopping": "⏹️ Quest Bot toqtatılmaqta. Maǵlıwmatlar bazası zıyarat nusqası tayarlanbaqta.",
    "database_backup_caption": "Quest Bot maǵlıwmatlar bazası zıyarat nusqası ({timestamp} UTC).",
    "database_backup_failed": "Maǵlıwmatlar bazası zıyarat nusqasın jaratıp bolmadı. Server jurnalın tekseriń.",
    "database_backup_delivery_failed": "Zıyarat faylın jiberip bolmadı. Server jurnalın tekseriń.",
    "btn_start_quest": "▶️ Kvestti baslaw",
    "btn_continue_quest": "⏩ Dawam etiw",
    "quest_started_notice": "🚀 «{title}» kvesti baslandı!",
    "quest_started_hint": "Tayın bolǵanıńızda «{button}» túymesin basıń — soraw sonnan keyin jiberiledi.",
    "quest_started_waiting": "Birinshi basqısh óz waqtında baslanadı; tayın bolǵanda xabar beremiz.",
    "stage_available_notice": "🔔 «{title}» kvestinde {number}-basqısh tayın!",
    "stage_continue_hint": "Sorawdı alıw ushın «{button}» túymesin basıń.",
    "stage_not_started_yet": "Keyingi basqısh ele baslanmadı. Baslanıw waqtın kútiń.",
    "quest_stage_unavailable": "Házirge siz ushın ashıq soraw joq.",
    "btn_edit_start": "🕒 Baslanıw waqtın redaktorlaw",
    "ask_quest_start": "Jańa baslanıw waqtın Tashkent waqtı boyınsha jiberiń: YYYY-MM-DD HH:MM\nMısalı: 2026-10-03 18:30",
    "quest_start_edit_hint": "Aǵımdaǵı waqıt: {current}\nBelgilengen basqıshlar waqtı jańa baslanıw waqtına sáykes jıljıtıladı.",
    "invalid_quest_start": "⚠️ Sana formatı nadurıs yamasa waqıt ótip ketken.",
    "quest_start_updated": "✅ Kvest baslanıw waqtı jańalandı.",
    "quest_start_edit_closed": "⚠️ Baslanıw waqtın tek ele baslanbaǵan (belgilengen) kvestte ózgertiw múmkin.",
    "btn_delete_quest": "🗑️ Kvestti óshiriw",
    "btn_confirm_delete_quest": "🗑️ Awa, óshiriw",
    "confirm_delete_quest": "«{title}» kvestin óshiresiz be?\nKvest tek óshirilgen dep belgilenedi (delete = true) hám dizimlerden jasırınadı; maǵlıwmatlar bazadan óshirilmeydi.",
    "quest_deleted": "🗑️ Kvest óshirilgen dep belgilendi (delete = true). Maǵlıwmatlar bazada saqlanadı; onı tek bas administrator kóre aladı hám tikley aladı.",
    "btn_restore_quest": "♻️ Kvestti tiklew",
    "quest_restored": "♻️ Kvest tiklandi hám dizimlerde taǵı kórinedi.",
    "filter_deleted": "🗑 Óshirilgenler",
    "deleted_quest_view_title": "🗑 Óshirilgen kvest",
    "deleted_quest_view_body": "Bul kvest óshirilgen dep belgilengen (delete = true), sonlıqtan paydalanıwshılarǵa kórinbeydi. Maǵlıwmatlar bazada saqlanbaqta.",
    "ask_attempts_mode": "Barlıq basqıshlar ushın urınıslar sanı birdey me yamasa hár túrli me?",
    "attempts_same": "🔁 Birdey (barlıǵı ushın bitta san)",
    "attempts_different": "🔢 Hár túrli (hár bir basqısh ushın bólek)",
    "ask_common_attempts": "Barlıq basqıshlar ushın urınıslar sanın kiritiń (1–100):",
    "ambiguous_message_title": "❓ Bul juwap pa yamasa múrájat pa?",
    "ambiguous_message_body": "Sizde juwap kútilip atırǵan kvest basqıshı bar. Jibergen tekstińizdi qalay qabıl etiwin tańlań:",
    "btn_pending_as_answer": "🎯 «{title}» kvestine juwap",
    "btn_pending_as_ticket": "💬 Múrájat retinde jiberiw",
    "participant_message_heading_admin": "📩 Kvest administratorınan xabar · {title}",
    "error_generic": "Qátelik júz berdi. Qayta urınıp kóriń.",
    "btn_open_quest": "🧭 Kvestti ashıw",
    "invalid_quest_start_min": "⚠️ Baslanıw waqtı házirden keminde 10 minut keyin bolıwı kerek.",
    "btn_purge_quest": "🧨 Pútkilley óshiriw",
    "btn_confirm_purge_quest": "🧨 Awa, pútkilley óshiriw",
    "confirm_purge_quest": "🧨 «{title}» pútkilley óshiriledi: kvest, sorawlar, qatnasıwshılar hám juwaplar bazadan óshiriledi. Bul ámeldi qaytarıw múmkin emes.",
    "quest_purged": "🧨 «{title}» pútkilley óshirildi.",
    "deleted_quest_purge_hint": "Eger bul kvest pútkilley kerek bolmasa, onı bazadan tolıq óshiriw múmkin.",
    "admin_detail_title": "👤 Administrator: {name}",
    "admin_detail_body": "{role} · ID: {user_id}\n🧭 Kvestleri: {quests} · 🗑 Óshirilgenleri: {deleted}",
    "btn_admin_quests": "🧭 Kvestlerin kóriw",
    "btn_message_admin": "✉️ Xabar jiberiw",
    "admin_quests_title": "🧭 {name} kvestleri",
    "admin_quests_empty": "Bul administratordıń kvestleri joq.",
    "ask_admin_message": "✉️ {name} ǵa jiberiletuǵın xabardı jazıń (1–2000 belgi):",
    "admin_message_sent": "✅ Xabar {name} ǵa jiberildi.",
    "admin_message_heading": "📩 Bas administrator xabarı",
    "logs_terminal_hint": "🖥 Aqırǵı {count} jazıw · jańalaw ushın «{button}» túymesin basıń.",
    "btn_refresh": "🔄 Jańalaw",
    "no_admins": "📭 Administratorlar joq.",
}



